import type { Locale } from "@/content/site-content";
type Item = { title: string; description: string };
export type AboutContent = {
  hero:{eyebrow:string;title:string;description:string;slogans:string[]};
  director:{label:string;title:string;message:string;quote:string;signature:string};
  story:{label:string;title:string;description:string;elements:Item[];slogans:string[]};
  mission:{label:string;title:string;description:string;items:Item[]};
  vision:{label:string;title:string;description:string;ambitions:string[];slogans:string[]};
  philosophy:{label:string;title:string;description:string;items:Item[]};
  excellence:{label:string;title:string;description:string;capabilities:string[];quote:string};
  community:{label:string;title:string;description:string;items:Item[];slogans:string[]};
  commitment:{label:string;title:string;description:string;services:Item[]};
  values:{label:string;title:string;description:string;items:Item[]};
  cta:{label:string;title:string;description:string;motto:string[];actions:string[]};
};

export const aboutContent:Record<Locale,AboutContent>={
en:{
  hero:{eyebrow:"About the International Language & Pathway Center",title:"Excellence in Education. Commitment to Student Success.",description:"The Center was established to help students from around the world make a confident transition into higher education and prepare for meaningful participation in an increasingly connected world. At the UdeM Brossard Campus, language, academic capability, and personal growth become one integrated journey.",slogans:["Empowering Students","Advancing Learning","Building Futures"]},
  director:{label:"Message from the Director",title:"Education is one of the most powerful forces for personal growth, social progress, and global understanding.",message:"Our responsibility extends far beyond language instruction or admission preparation. We create an environment where students learn to trust their abilities, respond to challenge with resilience, ask better questions, and take ownership of their future. Every learner arrives with a different story; our work is to recognize that potential and help turn it into confident action.",quote:"We prepare students not only for university, but for a lifetime of learning and leadership.",signature:"Executive Director · International Language & Pathway Center"},
  story:{label:"Our story",title:"Created for the changing needs of international students.",description:"The Center was founded on a clear observation: successful transition into higher education requires more than a language score. Students need an integrated environment where communication, academic practice, university culture, and personal support develop together.",elements:[{title:"Language development",description:"Bilingual communication for academic participation, daily life, and future opportunity."},{title:"Academic preparation",description:"Research, writing, analysis, presentation, collaboration, and independent learning."},{title:"University readiness",description:"Understanding expectations, systems, responsibilities, and the habits behind success."},{title:"Student success support",description:"Personal guidance from application and arrival through progression and future planning."}],slogans:["A Foundation Built on Academic Excellence","A Future Focused on Student Success"]},
  mission:{label:"Our mission",title:"Transform potential into lasting academic capability.",description:"Our mission is to provide rigorous, supportive, and internationally minded learning experiences that prepare students for academic success, personal growth, and global engagement.",items:[{title:"Academic excellence",description:"Maintain demanding, transparent standards that reflect university-level thinking, communication, and responsibility."},{title:"Student success",description:"Provide personalized support throughout the student journey, recognizing that progress is both academic and personal."},{title:"Global citizenship",description:"Build intercultural understanding, respect for difference, and the ability to participate thoughtfully in a connected world."},{title:"Lifelong learning",description:"Cultivate curiosity, adaptability, reflection, and the desire to continue growing long after a program ends."}]},
  vision:{label:"Our vision",title:"A leading international center for language, pathway, and academic preparation.",description:"We aspire to set a standard for university-transition education: ambitious in its academic expectations, personal in its support, bilingual in its environment, and global in its outlook.",ambitions:["Expand access to high-quality education","Strengthen international academic collaboration","Support responsible student mobility","Advance bilingual and multicultural learning","Prepare future leaders for a changing world"],slogans:["Educating Minds","Inspiring Possibilities","Transforming Futures"]},
  philosophy:{label:"Our educational philosophy",title:"Students are not passengers in their education.",description:"Learning becomes transformative when students are active, challenged, supported, and trusted with increasing responsibility.",items:[{title:"Inspire curiosity",description:"Encourage questions, exploration, intellectual risk, and the desire to understand ideas more deeply."},{title:"Foster independence",description:"Help students plan, make decisions, manage learning, and become confident self-directed learners."},{title:"Promote critical thinking",description:"Evaluate evidence, compare perspectives, identify assumptions, and form reasoned conclusions."},{title:"Encourage collaboration",description:"Learn how to listen, contribute, negotiate, lead, and work effectively across difference."},{title:"Build confidence",description:"Use authentic tasks, meaningful feedback, and visible progress to turn uncertainty into capability."}]},
  excellence:{label:"Academic excellence",title:"University success is built through disciplined practice.",description:"Our programs reflect the realities of higher education. Students repeatedly practise the work—reading, researching, writing, presenting, questioning, collaborating, and revising—that turns preparation into genuine readiness.",capabilities:["Academic communication","Research competence","Analytical thinking","Leadership potential","Professional readiness"],quote:"Excellence is not an outcome. It is a process of continuous growth."},
  community:{label:"Our global community",title:"Diversity makes learning wider, sharper, and more human.",description:"Students from different countries, cultures, languages, and educational systems learn with and from one another. The result is a community where local learning continuously connects to global experience.",items:[{title:"Cultural exchange",description:"Share traditions, experiences, questions, and ways of seeing the world."},{title:"Global awareness",description:"Understand how ideas and decisions affect people across communities and borders."},{title:"Respect for diversity",description:"Build a learning culture where different identities and perspectives are valued."},{title:"International collaboration",description:"Practise communication and teamwork across languages, disciplines, and cultures."}],slogans:["Local Learning","Global Perspectives"]},
  commitment:{label:"Our commitment to student success",title:"Support at every stage, not only when something goes wrong.",description:"A strong institution creates clear ways for students to ask questions, make informed decisions, address challenges early, and stay connected to their goals.",services:[{title:"Academic advising",description:"Program choice, goal setting, progression reviews, and future study planning."},{title:"Learning support",description:"Writing, study strategy, research guidance, tutoring, and academic coaching."},{title:"Student services",description:"Arrival, housing information, insurance guidance, daily life, and community connection."},{title:"Career development",description:"Professional communication, career exploration, networking, and internship readiness."},{title:"University readiness",description:"Workshops, campus orientation, academic integrity, and transition preparation."}]},
  values:{label:"Our values",title:"Five principles guide every decision we make.",description:"Our values shape the classroom, the student experience, our partnerships, and the standards by which we evaluate our own work.",items:[{title:"Excellence",description:"Pursue high standards with discipline, care, and the conviction that every learner can grow."},{title:"Integrity",description:"Act with honesty, transparency, accountability, and respect for academic responsibility."},{title:"Inclusion",description:"Create an environment where students feel respected, represented, safe, and able to contribute."},{title:"Innovation",description:"Remain curious, responsive, and willing to improve how education is designed and delivered."},{title:"Collaboration",description:"Build stronger outcomes through shared knowledge, dialogue, partnership, and collective effort."}]},
  cta:{label:"Join our academic community",title:"Build Your Future With Us",description:"Whether your goal is language confidence, university admission, academic advancement, or long-term professional growth, begin in a community that takes your ambitions seriously.",motto:["Excellence","Opportunity","Transformation"],actions:["Apply Now","Meet Our Team","Contact Us"]}
},
fr:{
 hero:{eyebrow:"À propos du Centre international",title:"Excellence en éducation. Engagement envers la réussite.",description:"Le Centre aide les étudiants du monde entier à réussir leur transition vers les études supérieures et à participer à un monde interconnecté. Au campus UdeM de Brossard, langues, capacité académique et croissance personnelle forment un même parcours.",slogans:["Donner les moyens","Faire progresser l'apprentissage","Construire l'avenir"]},
 director:{label:"Message de la direction",title:"L'éducation est l'une des forces les plus puissantes de croissance, de progrès social et de compréhension mondiale.",message:"Notre responsabilité dépasse l'enseignement des langues et la préparation à l'admission. Nous créons un milieu où les étudiants apprennent à croire en leurs capacités, à répondre aux défis avec résilience, à poser de meilleures questions et à prendre leur avenir en main.",quote:"Nous préparons les étudiants non seulement pour l'université, mais pour toute une vie d'apprentissage et de leadership.",signature:"Direction générale · Centre international de langues et de parcours"},
 story:{label:"Notre histoire",title:"Créé pour répondre aux besoins changeants des étudiants internationaux.",description:"Le Centre repose sur une conviction : une transition réussie exige plus qu'un résultat linguistique. Communication, pratique académique, culture universitaire et soutien personnel doivent évoluer ensemble.",elements:[{title:"Développement linguistique",description:"Communication bilingue pour les études, la vie et les possibilités futures."},{title:"Préparation académique",description:"Recherche, rédaction, analyse, présentation, collaboration et autonomie."},{title:"Préparation universitaire",description:"Attentes, systèmes, responsabilités et habitudes de réussite."},{title:"Soutien à la réussite",description:"Accompagnement de la demande jusqu'à la progression et au projet futur."}],slogans:["Une fondation d'excellence académique","Un avenir centré sur la réussite"]},
 mission:{label:"Notre mission",title:"Transformer le potentiel en capacité durable.",description:"Offrir des expériences rigoureuses, bienveillantes et internationales qui préparent à la réussite, à la croissance personnelle et à l'engagement mondial.",items:[{title:"Excellence académique",description:"Des normes exigeantes et transparentes reflétant la pensée et la responsabilité universitaires."},{title:"Réussite étudiante",description:"Un soutien personnalisé reconnaissant que la progression est académique et personnelle."},{title:"Citoyenneté mondiale",description:"Compréhension interculturelle, respect de la différence et participation réfléchie."},{title:"Apprentissage continu",description:"Curiosité, adaptabilité, réflexion et désir de continuer à grandir."}]},
 vision:{label:"Notre vision",title:"Un centre international de référence en langues et parcours universitaires.",description:"Établir une norme pour la transition universitaire : ambitieuse, personnelle, bilingue et mondiale.",ambitions:["Élargir l'accès à une éducation de qualité","Renforcer la collaboration internationale","Soutenir la mobilité étudiante","Promouvoir l'apprentissage bilingue et multiculturel","Préparer les leaders d'un monde en changement"],slogans:["Éduquer les esprits","Inspirer les possibilités","Transformer les avenirs"]},
 philosophy:{label:"Notre philosophie éducative",title:"Les étudiants ne sont pas passagers de leur éducation.",description:"L'apprentissage transforme lorsqu'il est actif, exigeant, accompagné et de plus en plus autonome.",items:[{title:"Inspirer la curiosité",description:"Encourager questions, exploration et désir de comprendre."},{title:"Favoriser l'autonomie",description:"Planifier, décider et devenir un apprenant responsable."},{title:"Développer la pensée critique",description:"Évaluer les preuves, comparer et conclure avec raison."},{title:"Encourager la collaboration",description:"Écouter, contribuer, négocier et travailler entre différences."},{title:"Bâtir la confiance",description:"Transformer l'incertitude en capacité par la pratique et la rétroaction."}]},
 excellence:{label:"Excellence académique",title:"La réussite universitaire se construit par une pratique disciplinée.",description:"Les étudiants pratiquent la lecture, la recherche, la rédaction, la présentation, le questionnement, la collaboration et la révision.",capabilities:["Communication académique","Compétence en recherche","Pensée analytique","Potentiel de leadership","Préparation professionnelle"],quote:"L'excellence n'est pas un résultat. C'est un processus de croissance continue."},
 community:{label:"Notre communauté mondiale",title:"La diversité rend l'apprentissage plus vaste et plus humain.",description:"Des étudiants de pays, cultures et systèmes différents apprennent ensemble et relient l'expérience locale au monde.",items:[{title:"Échange culturel",description:"Partager traditions, expériences et manières de voir."},{title:"Conscience mondiale",description:"Comprendre les effets des idées au-delà des frontières."},{title:"Respect de la diversité",description:"Valoriser les identités et perspectives différentes."},{title:"Collaboration internationale",description:"Communiquer et travailler entre langues et cultures."}],slogans:["Apprentissage local","Perspectives mondiales"]},
 commitment:{label:"Notre engagement envers la réussite",title:"Un soutien à chaque étape, pas seulement en cas de difficulté.",description:"Les étudiants disposent de moyens clairs pour poser des questions, décider et rester reliés à leurs objectifs.",services:[{title:"Conseils académiques",description:"Programme, objectifs, progression et études futures."},{title:"Soutien à l'apprentissage",description:"Rédaction, stratégies, recherche, tutorat et coaching."},{title:"Services étudiants",description:"Arrivée, logement, assurance, vie quotidienne et communauté."},{title:"Développement de carrière",description:"Communication, exploration, réseautage et stages."},{title:"Préparation universitaire",description:"Ateliers, orientation, intégrité et transition."}]},
 values:{label:"Nos valeurs",title:"Cinq principes guident chaque décision.",description:"Ils façonnent les cours, l'expérience, les partenariats et nos propres standards.",items:[{title:"Excellence",description:"Poursuivre de hauts standards avec rigueur et soin."},{title:"Intégrité",description:"Agir avec honnêteté, transparence et responsabilité."},{title:"Inclusion",description:"Créer un milieu respectueux où chacun peut contribuer."},{title:"Innovation",description:"Rester curieux et améliorer l'éducation."},{title:"Collaboration",description:"Partager savoir, dialogue et effort collectif."}]},
 cta:{label:"Rejoignez notre communauté",title:"Construisez votre avenir avec nous",description:"Commencez dans une communauté qui prend au sérieux vos ambitions linguistiques, universitaires et professionnelles.",motto:["Excellence","Possibilité","Transformation"],actions:["Faire une demande","Rencontrer l'équipe","Nous joindre"]}
},
zh:{
 hero:{eyebrow:"关于国际语言与大学衔接中心",title:"以卓越教育，成就学生更远的未来。",description:"中心致力于帮助全球学生自信过渡到高等教育，并为日益互联的世界做好准备。在蒙大 Brossard 校区，语言、学术能力和个人成长被连接成一段完整旅程。",slogans:["成就学生","推动学习","面向未来"]},
 director:{label:"院长致辞",title:"教育，是个人成长、社会进步与全球理解最有力量的路径之一。",message:"我们的责任远不止语言教学或入学准备。我们希望创造一个让学生相信自身能力、以韧性面对挑战、提出更好问题并主动掌握未来的环境。每位学习者都有不同故事，我们的工作是看见潜力，并帮助它成为自信行动。",quote:"我们不只是为大学做准备，更是为终身学习与未来领导力做准备。",signature:"执行院长 · 国际语言与大学衔接中心"},
 story:{label:"我们的故事",title:"因应国际学生不断变化的升学需求而创立。",description:"中心建立在一个清晰判断之上：成功过渡到高等教育，需要的不只是一项语言成绩。沟通、学术实践、大学文化和个人支持必须共同发展。",elements:[{title:"语言发展",description:"用于学术参与、日常生活和未来机会的双语沟通。"},{title:"学术准备",description:"研究、写作、分析、演讲、协作和独立学习。"},{title:"大学准备度",description:"理解大学要求、系统、责任和成功习惯。"},{title:"学生成功支持",description:"从申请、抵达到学术进展和未来规划的个性化指导。"}],slogans:["建立在学术卓越基础上","聚焦学生成功的未来"]},
 mission:{label:"我们的使命",title:"将潜力转化为持久的学术能力。",description:"提供严谨、支持充分且具有国际视野的学习体验，为学术成功、个人成长和全球参与做好准备。",items:[{title:"学术卓越",description:"坚持反映大学级思维、沟通和责任的严格透明标准。"},{title:"学生成功",description:"在整个学生旅程中提供个性化支持，关注学术与个人双重成长。"},{title:"全球公民意识",description:"培养跨文化理解、尊重差异和参与互联世界的能力。"},{title:"终身学习",description:"培养好奇心、适应力、反思能力及持续成长的愿望。"}]},
 vision:{label:"我们的愿景",title:"成为领先的国际语言、衔接与学术准备中心。",description:"为大学过渡教育建立标准：学术要求有雄心、学生支持有温度、学习环境双语化、发展视野全球化。",ambitions:["扩大优质教育获取","加强国际学术合作","支持负责任的学生流动","推动双语与多元文化学习","培养面向变革世界的未来领袖"],slogans:["启迪思想","激发可能","转变未来"]},
 philosophy:{label:"我们的教育理念",title:"学生不是教育旅程中的乘客。",description:"当学生主动参与、受到挑战、获得支持并承担越来越多责任时，学习才会真正产生转变。",items:[{title:"激发好奇心",description:"鼓励提问、探索、思想冒险和深入理解。"},{title:"培养独立性",description:"帮助学生规划、决策、管理学习并成为自主学习者。"},{title:"促进批判性思维",description:"评估证据、比较观点、识别假设并形成结论。"},{title:"鼓励协作",description:"学会倾听、贡献、协商、领导并跨越差异合作。"},{title:"建立信心",description:"通过真实任务、有效反馈和可见进步把不确定变成能力。"}]},
 excellence:{label:"学术卓越",title:"大学成功建立在持续而有纪律的实践上。",description:"课程反映真实高等教育要求。学生反复实践阅读、研究、写作、演讲、提问、协作和修改，将准备转化为真正的大学准备度。",capabilities:["学术沟通能力","研究能力","分析思维能力","领导力潜质","职业准备度"],quote:"卓越不是结果，而是持续成长的过程。"},
 community:{label:"我们的全球社区",title:"多元让学习更加广阔、敏锐且富有人性。",description:"来自不同国家、文化、语言和教育体系的学生相互学习，让本地学习持续连接全球经验。",items:[{title:"跨文化交流",description:"分享传统、经历、问题和理解世界的方式。"},{title:"全球意识",description:"理解思想与决定如何影响不同社区和国家。"},{title:"尊重多元",description:"建立重视不同身份和观点的学习文化。"},{title:"国际协作",description:"跨越语言、学科和文化实践沟通与团队合作。"}],slogans:["本地学习","全球视野"]},
 commitment:{label:"我们对学生成功的承诺",title:"每个阶段都有支持，而不只是在出现问题之后。",description:"成熟机构应让学生能够清楚提问、明智决策、及早应对挑战并持续连接目标。",services:[{title:"学术咨询",description:"课程选择、目标制定、进度评估和未来升学规划。"},{title:"学习支持",description:"写作、学习策略、研究指导、辅导和学业教练。"},{title:"学生服务",description:"抵达、住房信息、保险指导、日常生活与社区连接。"},{title:"职业发展指导",description:"专业沟通、职业探索、人脉和实习准备。"},{title:"大学准备项目",description:"工作坊、校园指导、学术诚信与过渡准备。"}]},
 values:{label:"我们的价值观",title:"五大核心价值指导每一个决定。",description:"价值观塑造课堂、学生体验、合作关系以及我们评价自身工作的标准。",items:[{title:"卓越",description:"以纪律、用心和对每位学生成长的信念追求高标准。"},{title:"诚信",description:"以诚实、透明、责任和学术原则行事。"},{title:"包容",description:"创造让学生受到尊重、感到安全并能够贡献的环境。"},{title:"创新",description:"保持好奇，持续改进教育设计与实施方式。"},{title:"协作",description:"通过共享知识、对话、伙伴关系和共同努力创造更强成果。"}]},
 cta:{label:"加入我们的学术社区",title:"在这里，开启更有准备的未来。",description:"无论你的目标是语言信心、大学录取、学术提升还是长期职业成长，都可以从一个认真对待你理想的社区开始。",motto:["卓越","机遇","转变"],actions:["立即申请","认识我们的团队","联系我们"]}
}}
