import type { Locale } from "@/content/site-content";

type Item = { title: string; description: string };

export type AdmissionsContent = {
  hero: { eyebrow: string; title: string; description: string; slogans: string[]; actions: string[] };
  applicants: { label: string; title: string; description: string; items: Item[] };
  requirements: { label: string; title: string; description: string; items: Item[]; note: string };
  process: { label: string; title: string; description: string; steps: Item[] };
  intakes: { label: string; title: string; description: string; terms: Array<{ season: string; month: string; detail: string }> };
  support: { label: string; title: string; description: string; items: Item[] };
  tuition: { label: string; title: string; description: string; prices: Array<{ amount: string; label: string; detail: string }>; slogans: string[]; note: string };
  whyApply: { label: string; title: string; description: string; items: Item[] };
  faq: { label: string; title: string; items: Array<{ question: string; answer: string }> };
  cta: { label: string; title: string; description: string; motto: string; actions: string[] };
};

export const admissionsContent: Record<Locale, AdmissionsContent> = {
  en: {
    hero: { eyebrow: "Admissions · International Language & Pathway Center", title: "Your Future Starts Here", description: "We welcome motivated students from around the world who are seeking academic preparation, language development, and a supported pathway to higher education. Our admissions team helps each applicant identify the right program, level, and entry point.", slogans: ["Apply with Confidence", "Learn with Purpose", "Succeed with Excellence"], actions: ["Apply Now", "Speak with an Admissions Advisor"] },
    applicants: { label: "Who can apply?", title: "Different starting points. One shared ambition.", description: "Applications are considered from learners with varied academic histories, language levels, ages, and future plans.", items: [{ title: "International students", description: "Students planning to continue their education in Canada and seeking structured preparation for the academic and cultural transition." }, { title: "Secondary school graduates", description: "Graduates preparing for higher education who want stronger study skills, language confidence, or subject foundations." }, { title: "University-bound students", description: "Applicants seeking academic preparation and pathway support before entering a college, university, or professional program." }, { title: "Adult learners", description: "Motivated learners returning to education or strengthening language and academic capability for a new professional direction." }] },
    requirements: { label: "Program entry requirements", title: "A complete application helps us recommend the right pathway.", description: "Requirements vary by program, entry level, and applicant background. The initial review focuses on readiness, educational history, language needs, and future goals.", items: [{ title: "Academic records", description: "Official transcripts, certificates, diplomas, or other proof of previous education. Certified translations may be requested." }, { title: "Identification documents", description: "A valid passport or government-issued identity document matching the legal name used in the application." }, { title: "Language assessment", description: "Existing test results may be reviewed. A placement assessment is used where needed to identify the appropriate starting level." }, { title: "Supporting documents", description: "A study plan, résumé, reference, portfolio, or additional program-specific information may be requested." }], note: "Applicants may be invited to an academic consultation to discuss their background, educational objectives, and recommended learning pathway." },
    process: { label: "Application process", title: "Six clear steps from application to first day.", description: "Our team keeps applicants informed at every stage and identifies missing information early so the process can move forward confidently.", steps: [{ title: "Submit an online application", description: "Complete the application form, select a preferred program and intake, and upload the requested documents." }, { title: "Application review", description: "The admissions team reviews academic history, language background, educational goals, and document completeness." }, { title: "Academic consultation", description: "Meet with an advisor when required to discuss goals, placement, program fit, and the recommended pathway." }, { title: "Receive an offer", description: "Qualified applicants receive a formal offer outlining the program, intake, conditions, tuition, and next steps." }, { title: "Confirm enrolment", description: "Accept the offer, pay the required deposit, confirm the place, and complete registration preparations." }, { title: "Begin your studies", description: "Attend orientation, meet the student support team, and begin the academic journey at the Brossard Campus." }] },
    intakes: { label: "Intakes & academic calendar", title: "Three principal opportunities to begin each year.", description: "Program availability and application deadlines are confirmed for each intake. Selected language and workshop formats may offer additional start dates.", terms: [{ season: "Fall Intake", month: "September", detail: "The main academic intake with the broadest selection of language, pathway, and foundation programs." }, { season: "Winter Intake", month: "January", detail: "A new-year entry point for students ready to begin language development or academic preparation." }, { season: "Summer Intake", month: "May", detail: "A focused start that can support language acceleration, transition preparation, and fall planning." }] },
    support: { label: "International student support", title: "Preparation for Canada begins before arrival.", description: "Students receive practical information and coordinated guidance to make the transition into study and daily life in Greater Montréal clearer.", items: [{ title: "Arrival assistance", description: "Pre-arrival checklists, travel preparation, first-week guidance, and information for reaching Brossard." }, { title: "Housing guidance", description: "Orientation to rental options, neighbourhoods, budgeting, leases, and trusted accommodation resources." }, { title: "Health insurance information", description: "Guidance on required coverage, enrolment steps, policy periods, and access to health resources." }, { title: "Settlement support", description: "Practical information about banking, transit, mobile service, daily essentials, and life in Québec." }, { title: "Academic orientation", description: "Introduction to campus systems, class expectations, support services, study habits, and academic integrity." }] },
    tuition: { label: "Tuition & financial information", title: "Plan the complete cost of study with clarity.", description: "The following planning figures reflect a premium university-campus pathway experience with bilingual academic instruction, small-group learning, personalized advising, and integrated student support. Each offer includes an individualized fee schedule based on program, level, study load, and duration.", prices: [{ amount: "CAD 3,850", label: "Language session", detail: "Estimated tuition from, per intensive six-week session" }, { amount: "CAD 11,600", label: "Pathway term", detail: "Estimated tuition from, per full-time academic term" }, { amount: "CAD 23,200", label: "Academic year", detail: "Estimated two-term pathway or foundation tuition" }, { amount: "CAD 165", label: "Application fee", detail: "One-time, non-refundable application review fee" }, { amount: "CAD 1,200", label: "Health coverage", detail: "Estimated annual international student insurance" }, { amount: "CAD 590", label: "Student services", detail: "Estimated annual orientation, advising, and campus services" }], slogans: ["Transparent", "Premium", "Student-Focused"], note: "All amounts are in Canadian dollars and are planning estimates. Final tuition, compulsory fees, payment dates, refund terms, and insurance charges appear in the official offer and enrolment agreement." },
    whyApply: { label: "Why apply to the Center?", title: "Preparation designed around the whole student journey.", description: "Students join a connected environment where language, academic development, university planning, and personal support work together.", items: [{ title: "University environment", description: "Learn at the Université de Montréal Brossard Campus and become familiar with university culture before future degree study." }, { title: "Academic preparation", description: "Develop research, writing, critical thinking, presentation, collaboration, and independent learning." }, { title: "Language development", description: "Strengthen French and English for academic participation, daily life, and future professional opportunity." }, { title: "Personalized support", description: "Receive guidance from application and arrival through academic progress, program planning, and graduation." }, { title: "Global opportunity", description: "Build bilingual confidence, international perspective, and the transferable skills needed for future study and work." }] },
    faq: { label: "Admissions FAQ", title: "Answers before you apply.", items: [{ question: "Do I need proof of French or English before applying?", answer: "Not for every program. Options are available for different language backgrounds and levels. Existing results may be reviewed, and a placement assessment can determine the most appropriate starting point." }, { question: "Can international students apply?", answer: "Yes. We welcome applications from qualified students around the world and provide guidance on documents, arrival preparation, and program selection." }, { question: "Is academic advising available?", answer: "Yes. Advisors help applicants understand program options, entry level, study planning, and the pathway best aligned with their goals." }, { question: "Can I continue to higher education after pathway studies?", answer: "Yes. Pathway and preparation programs are specifically designed to strengthen university readiness and support future academic success. Students continue to the institutions and programs for which they meet admission requirements." }] },
    cta: { label: "Apply today", title: "Take the first step toward your future.", description: "Your academic journey begins with one clear decision. Tell us about your background and goals, and our admissions team will help you identify the next step.", motto: "Preparing Students for University Success", actions: ["Apply Now", "Request Information", "Contact Admissions"] },
  },
  fr: {
    hero: { eyebrow: "Admission · Centre international de langues et de parcours", title: "Votre avenir commence ici", description: "Nous accueillons des étudiants motivés du monde entier à la recherche d'une préparation académique, d'un développement linguistique et d'un parcours accompagné vers les études supérieures.", slogans: ["Postuler avec confiance", "Apprendre avec intention", "Réussir avec excellence"], actions: ["Faire une demande", "Parler à un conseiller"] },
    applicants: { label: "Qui peut présenter une demande?", title: "Des points de départ différents, une ambition commune.", description: "Nous considérons des parcours scolaires, niveaux linguistiques, âges et projets variés.", items: [{ title: "Étudiants internationaux", description: "Se préparer à poursuivre des études au Canada et à réussir la transition académique et culturelle." }, { title: "Diplômés du secondaire", description: "Renforcer méthodes d'étude, confiance linguistique et fondements disciplinaires avant le supérieur." }, { title: "Futurs étudiants universitaires", description: "Obtenir une préparation académique et un accompagnement avant un collège, une université ou un programme professionnel." }, { title: "Apprenants adultes", description: "Revenir aux études ou renforcer ses capacités linguistiques et académiques pour une nouvelle direction." }] },
    requirements: { label: "Conditions d'admission", title: "Un dossier complet nous aide à recommander le bon parcours.", description: "Les exigences varient selon le programme, le niveau et le profil. L'analyse porte sur la préparation, les études antérieures, les besoins linguistiques et les objectifs.", items: [{ title: "Dossiers scolaires", description: "Relevés officiels, certificats, diplômes ou preuves d'études; des traductions certifiées peuvent être demandées." }, { title: "Pièces d'identité", description: "Passeport valide ou document gouvernemental correspondant au nom légal de la demande." }, { title: "Évaluation linguistique", description: "Les résultats existants peuvent être étudiés; un test de classement détermine le niveau au besoin." }, { title: "Documents complémentaires", description: "Projet d'études, CV, référence, portfolio ou renseignements propres au programme." }], note: "Une consultation académique peut être demandée afin de discuter du parcours, des objectifs et du programme recommandé." },
    process: { label: "Processus de demande", title: "Six étapes claires jusqu'au premier jour.", description: "L'équipe informe le candidat à chaque étape et identifie rapidement les renseignements manquants.", steps: [{ title: "Soumettre la demande", description: "Remplir le formulaire, choisir le programme et la rentrée, puis téléverser les documents." }, { title: "Analyse du dossier", description: "Évaluation des études, des langues, des objectifs et de la conformité du dossier." }, { title: "Consultation académique", description: "Rencontrer un conseiller au besoin pour discuter du niveau et du parcours recommandé." }, { title: "Recevoir une offre", description: "L'offre officielle précise programme, rentrée, conditions, droits et prochaines étapes." }, { title: "Confirmer l'inscription", description: "Accepter l'offre, verser le dépôt, réserver sa place et préparer l'inscription." }, { title: "Commencer les études", description: "Participer à l'orientation et commencer le parcours au campus de Brossard." }] },
    intakes: { label: "Rentrées et calendrier", title: "Trois occasions principales de commencer chaque année.", description: "Les programmes et dates limites sont confirmés pour chaque rentrée; certaines formations peuvent offrir d'autres dates.", terms: [{ season: "Rentrée d'automne", month: "Septembre", detail: "Rentrée principale et choix le plus vaste de programmes linguistiques, de parcours et de fondements." }, { season: "Rentrée d'hiver", month: "Janvier", detail: "Un nouveau départ pour amorcer le développement linguistique ou la préparation académique." }, { season: "Rentrée d'été", month: "Mai", detail: "Début ciblé pour accélérer les langues, préparer la transition et planifier l'automne." }] },
    support: { label: "Soutien aux étudiants internationaux", title: "La préparation au Canada commence avant l'arrivée.", description: "Des renseignements pratiques et un accompagnement coordonné rendent la transition vers Montréal plus claire.", items: [{ title: "Aide à l'arrivée", description: "Listes de vérification, préparation du voyage et renseignements pour rejoindre Brossard." }, { title: "Conseils de logement", description: "Options locatives, quartiers, budget, baux et ressources fiables." }, { title: "Assurance maladie", description: "Couverture obligatoire, inscription, périodes de protection et accès aux ressources." }, { title: "Aide à l'installation", description: "Banque, transport, téléphone, besoins quotidiens et vie au Québec." }, { title: "Orientation académique", description: "Systèmes du campus, attentes, services, méthodes d'étude et intégrité." }] },
    tuition: { label: "Droits et information financière", title: "Planifiez le coût complet avec clarté.", description: "Ces montants reflètent une expérience de parcours universitaire haut de gamme : enseignement académique bilingue, petits groupes, conseils personnalisés et soutien étudiant intégré. Chaque offre comprend un échéancier personnalisé selon le programme, le niveau et la durée.", prices: [{ amount: "3 850 CAD", label: "Session de langue", detail: "Estimation à partir de, par session intensive de six semaines" }, { amount: "11 600 CAD", label: "Trimestre de parcours", detail: "Estimation à partir de, par trimestre à temps plein" }, { amount: "23 200 CAD", label: "Année académique", detail: "Estimation pour deux trimestres de parcours ou fondements" }, { amount: "165 CAD", label: "Frais de demande", detail: "Frais uniques et non remboursables" }, { amount: "1 200 CAD", label: "Assurance santé", detail: "Estimation annuelle pour étudiants internationaux" }, { amount: "590 CAD", label: "Services étudiants", detail: "Orientation, conseils et services du campus" }], slogans: ["Transparent", "Haut de gamme", "Centré sur l'étudiant"], note: "Tous les montants sont en dollars canadiens et constituent des estimations. Les droits finaux, échéances, remboursements et assurances figurent dans l'offre officielle." },
    whyApply: { label: "Pourquoi présenter une demande?", title: "Une préparation pensée pour l'ensemble du parcours.", description: "Langues, développement académique, planification universitaire et soutien personnel travaillent ensemble.", items: [{ title: "Milieu universitaire", description: "Étudier au campus de Brossard de l'Université de Montréal et découvrir la culture universitaire." }, { title: "Préparation académique", description: "Développer recherche, rédaction, pensée critique, présentation et autonomie." }, { title: "Développement linguistique", description: "Renforcer français et anglais pour les études, la vie et les possibilités professionnelles." }, { title: "Soutien personnalisé", description: "Être accompagné de la demande jusqu'à la progression et à la diplomation." }, { title: "Possibilités mondiales", description: "Construire confiance bilingue, perspective internationale et compétences transférables." }] },
    faq: { label: "FAQ admission", title: "Des réponses avant de postuler.", items: [{ question: "Faut-il une preuve de français ou d'anglais?", answer: "Pas pour tous les programmes. Des options existent pour différents niveaux et un test de classement peut déterminer le point de départ." }, { question: "Les étudiants internationaux peuvent-ils postuler?", answer: "Oui. Nous accueillons les candidats qualifiés du monde entier et les guidons pour les documents et le choix du programme." }, { question: "L'orientation académique est-elle offerte?", answer: "Oui. Les conseillers aident à comprendre les options, le niveau d'entrée et le parcours adapté." }, { question: "Puis-je poursuivre des études supérieures après le parcours?", answer: "Oui. Les programmes renforcent la préparation universitaire. Les étudiants poursuivent vers les établissements dont ils satisfont les conditions d'admission." }] },
    cta: { label: "Postulez aujourd'hui", title: "Faites le premier pas vers votre avenir.", description: "Présentez votre parcours et vos objectifs; notre équipe vous aidera à identifier la prochaine étape.", motto: "Préparer les étudiants à la réussite universitaire", actions: ["Faire une demande", "Demander de l'information", "Contacter l'admission"] },
  },
  zh: {
    hero: { eyebrow: "招生信息 · 国际语言与大学衔接中心", title: "从申请开始，走向更清晰的未来。", description: "我们欢迎来自世界各地、希望提升语言能力、学术准备和大学衔接能力的学生。招生团队将协助每位申请人确认适合的课程、级别与入学起点。", slogans: ["从容申请", "目标清晰", "迈向卓越"], actions: ["立即申请", "咨询招生顾问"] },
    applicants: { label: "谁可以申请？", title: "不同的起点，共同的理想。", description: "我们接受具有不同学术经历、语言水平、年龄和未来计划的学习者申请。", items: [{ title: "国际学生", description: "计划在加拿大继续深造，并希望获得结构化学术与文化过渡准备的学生。" }, { title: "高中毕业生", description: "准备进入高等教育，希望加强学习方法、语言信心或专业基础的毕业生。" }, { title: "大学衔接学生", description: "进入学院、大学或专业课程前，希望获得学术准备与升学支持的申请人。" }, { title: "成人学习者", description: "重返教育，或为新的职业方向提升语言和学术能力的积极学习者。" }] },
    requirements: { label: "项目入学要求", title: "完整申请帮助我们推荐正确的学习路径。", description: "具体要求因课程、入学级别和个人背景而异。初步审核重点包括学术准备、教育经历、语言需求和未来目标。", items: [{ title: "学术记录", description: "官方成绩单、证书、文凭或其他学历证明；必要时需提供认证翻译件。" }, { title: "身份证件", description: "有效护照或政府签发的身份证件，姓名须与申请表中的法定姓名一致。" }, { title: "语言评估", description: "可审核已有语言成绩；必要时通过分级评估确定合适起始级别。" }, { title: "其他支持文件", description: "可能需要学习计划、简历、推荐信、作品集或课程指定资料。" }], note: "申请人可能需要参加学术咨询，讨论个人背景、教育目标以及推荐的学习路径。" },
    process: { label: "申请流程", title: "从提交申请到正式入学，六个清晰步骤。", description: "招生团队将在每个阶段及时沟通，并尽早确认缺失信息，使申请能够顺利推进。", steps: [{ title: "提交在线申请", description: "填写申请表，选择意向课程和入学批次，并上传所需材料。" }, { title: "招生审核", description: "招生团队评估学术经历、语言背景、教育目标及材料完整性。" }, { title: "学术咨询", description: "必要时与顾问讨论目标、分级、课程匹配度和推荐路径。" }, { title: "收到录取结果", description: "合格申请人获得列明课程、批次、条件、学费和后续步骤的正式 offer。" }, { title: "确认入学席位", description: "接受录取、支付所需定金、确认名额并完成注册准备。" }, { title: "正式开始学习", description: "参加新生指导、认识学生支持团队，并在 Brossard 校区开启学术旅程。" }] },
    intakes: { label: "入学批次与学年日历", title: "每年三个主要入学机会。", description: "各批次将确认具体开放课程和申请截止日期；部分语言课程和工作坊可能另设开课时间。", terms: [{ season: "秋季入学", month: "9 月", detail: "主要学术入学季，语言、大学衔接与学术基础课程选择最完整。" }, { season: "冬季入学", month: "1 月", detail: "适合准备开始语言发展或学术准备的新年入学起点。" }, { season: "夏季入学", month: "5 月", detail: "适合语言强化、过渡准备及秋季升学规划的集中起点。" }] },
    support: { label: "国际学生支持", title: "加拿大留学准备，从抵达之前开始。", description: "学生获得实用信息与协调指导，使进入大蒙特利尔地区的学习和日常生活更加清晰。", items: [{ title: "抵达协助", description: "行前清单、出行准备、第一周指导及前往 Brossard 的交通信息。" }, { title: "住房指导", description: "了解租房选择、社区、预算、租约和可靠住宿资源。" }, { title: "健康保险信息", description: "指导必要保险、注册步骤、保障周期和医疗资源使用。" }, { title: "安顿支持", description: "提供银行、交通、手机、日常生活及魁北克生活实用信息。" }, { title: "学术入学指导", description: "介绍校园系统、课堂要求、支持服务、学习习惯和学术诚信。" }] },
    tuition: { label: "学费与财务信息", title: "清楚规划完整学习成本。", description: "以下费用体现高端大学校园衔接体验，包括英法双语学术教学、小班学习、个性化升学指导及一体化学生支持。每份录取通知将根据课程、级别、学习量和时长提供个性化费用明细。", prices: [{ amount: "CAD 3,850", label: "语言课程", detail: "六周密集语言课程预估起价" }, { amount: "CAD 11,600", label: "衔接课程学期", detail: "全日制学术学期预估起价" }, { amount: "CAD 23,200", label: "完整学年", detail: "两学期衔接或学术基础课程预估" }, { amount: "CAD 165", label: "申请费", detail: "一次性、不可退还的申请审核费用" }, { amount: "CAD 1,200", label: "医疗保险", detail: "国际学生年度保险预估" }, { amount: "CAD 590", label: "学生服务费", detail: "年度新生指导、顾问及校园服务预估" }], slogans: ["透明", "高端定位", "以学生为中心"], note: "所有金额均为加元规划估算。最终学费、必缴费用、付款日期、退款政策和保险金额以正式录取通知及入学协议为准。" },
    whyApply: { label: "为什么申请本中心？", title: "围绕完整学生旅程设计的大学准备。", description: "学生进入一个将语言、学术发展、大学规划和个性化支持紧密连接的环境。", items: [{ title: "大学环境学习", description: "在蒙特利尔大学 Brossard 校区学习，进入未来学位课程前提前熟悉大学文化。" }, { title: "学术准备", description: "培养研究、写作、批判思维、演讲、协作和独立学习能力。" }, { title: "语言发展", description: "提升用于学术参与、日常生活和未来职业机会的英法能力。" }, { title: "个性化支持", description: "从申请和抵达到学术进展、课程规划及毕业获得持续指导。" }, { title: "全球机会", description: "建立双语信心、国际视野及未来学习和工作所需的可迁移能力。" }] },
    faq: { label: "招生常见问题", title: "申请前，你可能想了解这些问题。", items: [{ question: "申请前需要法语或英语能力证明吗？", answer: "并非所有课程都要求。不同语言背景和水平均有对应选择；学校可审核已有成绩，也可通过分级评估确定合适起点。" }, { question: "国际学生可以申请吗？", answer: "可以。我们欢迎全球合格学生申请，并提供材料准备、抵达安排和课程选择指导。" }, { question: "有学术指导吗？", answer: "有。顾问帮助申请人了解课程选择、入学级别、学习规划及最符合目标的路径。" }, { question: "完成衔接项目后能继续升学吗？", answer: "可以。衔接和准备课程专为加强大学准备与未来学术成功而设计。学生可继续申请符合其录取要求的院校和专业。" }] },
    cta: { label: "今天申请", title: "迈出通往未来的第一步。", description: "你的学术旅程从一个明确决定开始。告诉我们你的背景和目标，招生团队将帮助你确定下一步。", motto: "为学生的大学成功做好准备", actions: ["立即申请", "索取资料", "联系招生办公室"] },
  },
};
