import type { Locale } from "@/content/site-content";
type Item={title:string;description:string};
type Leader={name:string;role:string;initials:string;bio:string};
export type LeadershipContent={
 hero:{eyebrow:string;title:string;description:string;slogans:string[]};
 governance:{label:string;title:string;description:string;principles:Item[]};
 director:{label:string;title:string;message:string;promise:string;progression:string[];signature:string};
 board:{label:string;title:string;description:string;responsibilities:Item[];tags:string[]};
 team:{label:string;title:string;description:string;leaders:Leader[]};
 faculty:{label:string;title:string;description:string;commitments:Item[];slogans:string[]};
 quality:{label:string;title:string;description:string;processes:Item[]};
 values:{label:string;title:string;description:string;items:Item[]};
 cta:{label:string;title:string;description:string;motto:string;actions:string[]};
};

export const leadershipContent:Record<Locale,LeadershipContent>={
en:{
 hero:{eyebrow:"Leadership & Governance",title:"Guided by Academic Leadership",description:"Our leadership team, academic advisors, and education professionals work together to ensure that every part of the student experience reflects high standards of academic quality, integrity, care, and accountability.",slogans:["Academic Excellence","Strategic Vision","Student Success"]},
 governance:{label:"Governance philosophy",title:"Strong institutions are built on strong governance.",description:"Our governance framework connects educational purpose with responsible decision-making. Clear roles, evidence, dialogue, and regular review help the Center remain ambitious, transparent, and focused on students.",principles:[{title:"Academic quality",description:"Programs are designed, reviewed, and improved against clear learning outcomes and university-oriented standards."},{title:"Transparency",description:"Decisions, responsibilities, expectations, and student processes are communicated clearly and consistently."},{title:"Accountability",description:"Leaders and teams are responsible for outcomes, follow-through, ethical practice, and the quality of student experience."},{title:"Continuous improvement",description:"Data, feedback, reflection, and professional learning inform meaningful changes to programs and services."},{title:"Student-centered decisions",description:"Policies and priorities are evaluated through their real impact on learning, wellbeing, access, and future success."}]},
 director:{label:"Message from the Executive Director",title:"Education can transform lives, expand opportunity, and create lasting impact.",message:"At the Center, leadership means creating the conditions in which students and educators can do their best work. We combine clear academic expectations with personal support, responsible innovation, and a belief that every learner can develop beyond their current circumstances.",promise:"Our commitment is to help students cultivate the knowledge, skills, confidence, and character needed to achieve their goals and contribute meaningfully to the communities they join.",progression:["Education Creates Opportunity","Opportunity Creates Possibility","Possibility Creates the Future"],signature:"Dr. Isabelle Tremblay · Executive Director"},
 board:{label:"Academic Advisory Board",title:"Strategic guidance for standards, quality, and educational innovation.",description:"The Academic Advisory Board brings together experienced educators, researchers, and sector advisors to challenge assumptions, review direction, and ensure that programs remain rigorous, relevant, and responsive.",responsibilities:[{title:"Promote academic excellence",description:"Define ambitious expectations and protect the integrity of learning outcomes."},{title:"Support curriculum development",description:"Review program architecture, course progression, assessment, and alignment."},{title:"Enhance educational quality",description:"Use evidence and external perspective to strengthen teaching and student experience."},{title:"Encourage innovation",description:"Identify responsible new approaches to pedagogy, technology, and international education."},{title:"Strengthen student outcomes",description:"Keep progression, readiness, belonging, and long-term achievement at the center."}],tags:["Academic Leadership","Educational Innovation","Quality Assurance","Student Success"]},
 team:{label:"Our leadership team",title:"Experienced leadership across academics, students, international programs, and admissions.",description:"Each portfolio has a clear mandate while working as one team around institutional quality and student success.",leaders:[{name:"Dr. Isabelle Tremblay",role:"Executive Director",initials:"IT",bio:"Provides strategic leadership, institutional direction, partnership oversight, and accountability for the Center's mission."},{name:"Dr. Marc-André Gagnon",role:"Academic Director",initials:"MG",bio:"Leads curriculum development, faculty standards, academic quality, assessment, and educational outcomes."},{name:"Sofia Rahman",role:"Director of Student Success",initials:"SR",bio:"Oversees advising, student support, wellbeing, engagement, orientation, and progression initiatives."},{name:"David Chen",role:"Director of International Programs",initials:"DC",bio:"Leads international recruitment, institutional partnerships, global programs, and responsible student mobility."},{name:"Nadia Benali",role:"Director of Admissions",initials:"NB",bio:"Directs admissions policy, application review, enrolment planning, applicant communication, and registration management."}]},
 faculty:{label:"Faculty excellence",title:"Dedicated educators. Exceptional learning.",description:"Our faculty combine subject knowledge, academic rigour, intercultural awareness, and a deep commitment to student development. They teach with clarity, challenge students thoughtfully, and use feedback to make progress visible.",commitments:[{title:"Academic rigour",description:"Clear standards, meaningful assessment, strong subject knowledge, and university-level expectations."},{title:"Student engagement",description:"Active classrooms where students question, discuss, practise, create, and take responsibility."},{title:"Inclusive teaching",description:"Approaches that respect varied educational backgrounds, languages, strengths, and learning needs."},{title:"Professional development",description:"Ongoing learning in pedagogy, assessment, student support, technology, and disciplinary practice."},{title:"Educational innovation",description:"Purposeful use of new methods and tools when they improve understanding, participation, and outcomes."}],slogans:["Teaching with Purpose","Inspiring Achievement"]},
 quality:{label:"Quality assurance",title:"Quality is protected through a continuous cycle of review and improvement.",description:"We monitor not only what is taught, but what students learn, how consistently programs are delivered, and where the experience can become stronger.",processes:[{title:"Curriculum review",description:"Regular examination of relevance, sequence, workload, learning outcomes, and academic alignment."},{title:"Program assessment",description:"Analysis of performance, progression, completion, engagement, and readiness indicators."},{title:"Student feedback",description:"Structured opportunities for students to evaluate courses, services, support, and overall experience."},{title:"Faculty development",description:"Coaching, observation, peer exchange, professional learning, and teaching-resource development."},{title:"Academic integrity",description:"Clear expectations, responsible scholarship, fair assessment, and consistent academic processes."}]},
 values:{label:"Our values in action",title:"Values become meaningful only when they shape everyday decisions.",description:"Six shared principles define how we lead, teach, collaborate, support students, and hold ourselves accountable.",items:[{title:"Excellence",description:"Set high standards and pursue improvement with discipline and care."},{title:"Integrity",description:"Act honestly, transparently, ethically, and consistently."},{title:"Respect",description:"Listen seriously and recognize the dignity, experience, and contribution of others."},{title:"Inclusion",description:"Create conditions in which different people can participate, belong, and succeed."},{title:"Collaboration",description:"Share knowledge, responsibility, feedback, and credit to achieve stronger outcomes."},{title:"Innovation",description:"Question established practice and improve responsibly when better possibilities emerge."}]},
 cta:{label:"Leadership for tomorrow",title:"Building the Future Together",description:"Meet the educators and leaders creating an academic community defined by quality, responsibility, innovation, and a shared commitment to student success.",motto:"Excellence in Leadership. Excellence in Education.",actions:["Meet Our Faculty","Explore Our Programs","Contact Us"]}
},
fr:{
 hero:{eyebrow:"Direction et gouvernance",title:"Guidés par un leadership académique",description:"Direction, conseillers académiques et professionnels de l'éducation travaillent ensemble afin que chaque dimension de l'expérience respecte de hauts standards de qualité, d'intégrité et de responsabilité.",slogans:["Excellence académique","Vision stratégique","Réussite étudiante"]},
 governance:{label:"Philosophie de gouvernance",title:"Les institutions solides reposent sur une gouvernance solide.",description:"Notre cadre relie mission éducative et décision responsable. Rôles clairs, preuves, dialogue et révision régulière maintiennent le Centre ambitieux, transparent et centré sur l'étudiant.",principles:[{title:"Qualité académique",description:"Programmes conçus et améliorés selon des résultats clairs et des standards universitaires."},{title:"Transparence",description:"Décisions, responsabilités, attentes et processus sont communiqués clairement."},{title:"Responsabilité",description:"Les équipes répondent des résultats, du suivi, de l'éthique et de l'expérience."},{title:"Amélioration continue",description:"Données, rétroaction, réflexion et apprentissage professionnel guident les changements."},{title:"Décisions centrées sur l'étudiant",description:"Les priorités sont évaluées selon leur impact sur l'apprentissage et le bien-être."}]},
 director:{label:"Message de la direction générale",title:"L'éducation peut transformer des vies et créer un impact durable.",message:"Diriger signifie créer les conditions permettant aux étudiants et aux éducateurs de donner le meilleur d'eux-mêmes. Nous réunissons attentes claires, soutien personnel et innovation responsable.",promise:"Notre engagement est d'aider les étudiants à développer savoir, compétences, confiance et caractère pour atteindre leurs objectifs.",progression:["L'éducation crée l'occasion","L'occasion crée la possibilité","La possibilité crée l'avenir"],signature:"Dre Isabelle Tremblay · Directrice générale"},
 board:{label:"Conseil consultatif académique",title:"Une orientation stratégique pour les standards, la qualité et l'innovation.",description:"Des éducateurs, chercheurs et conseillers examinent l'orientation et assurent des programmes rigoureux et pertinents.",responsibilities:[{title:"Promouvoir l'excellence",description:"Définir des attentes ambitieuses et protéger les résultats."},{title:"Soutenir les programmes",description:"Réviser architecture, progression, évaluation et cohérence."},{title:"Améliorer la qualité",description:"Renforcer enseignement et expérience par les preuves."},{title:"Encourager l'innovation",description:"Explorer pédagogie, technologie et éducation internationale."},{title:"Renforcer les résultats",description:"Maintenir progression, préparation et réussite au centre."}],tags:["Leadership académique","Innovation éducative","Assurance qualité","Réussite étudiante"]},
 team:{label:"Notre équipe de direction",title:"Une expertise en académique, réussite, international et admission.",description:"Chaque portefeuille possède un mandat clair et travaille autour de la qualité et de la réussite.",leaders:[{name:"Dre Isabelle Tremblay",role:"Directrice générale",initials:"IT",bio:"Leadership stratégique, direction institutionnelle, partenariats et mission."},{name:"Dr Marc-André Gagnon",role:"Directeur académique",initials:"MG",bio:"Programmes, standards du corps enseignant, qualité et résultats."},{name:"Sofia Rahman",role:"Directrice de la réussite étudiante",initials:"SR",bio:"Conseils, soutien, bien-être, engagement, accueil et progression."},{name:"David Chen",role:"Directeur des programmes internationaux",initials:"DC",bio:"Recrutement international, partenariats et mobilité étudiante."},{name:"Nadia Benali",role:"Directrice de l'admission",initials:"NB",bio:"Politiques, analyse des demandes, inscriptions et communications."}]},
 faculty:{label:"Excellence du corps enseignant",title:"Des éducateurs engagés. Un apprentissage exceptionnel.",description:"Nos enseignants réunissent savoir disciplinaire, rigueur, conscience interculturelle et engagement envers le développement étudiant.",commitments:[{title:"Rigueur académique",description:"Standards clairs, évaluations significatives et attentes universitaires."},{title:"Engagement étudiant",description:"Classes actives où l'on questionne, pratique et crée."},{title:"Pédagogie inclusive",description:"Respect des parcours, langues, forces et besoins variés."},{title:"Développement professionnel",description:"Apprentissage continu en pédagogie, évaluation et technologie."},{title:"Innovation éducative",description:"Nouvelles méthodes lorsqu'elles améliorent compréhension et résultats."}],slogans:["Enseigner avec intention","Inspirer la réussite"]},
 quality:{label:"Assurance qualité",title:"La qualité est protégée par un cycle continu d'évaluation.",description:"Nous suivons ce qui est enseigné, ce qui est appris et les possibilités d'amélioration.",processes:[{title:"Révision des programmes",description:"Pertinence, séquence, charge, résultats et alignement."},{title:"Évaluation des programmes",description:"Performance, progression, achèvement et engagement."},{title:"Rétroaction étudiante",description:"Évaluation structurée des cours, services et soutien."},{title:"Développement du personnel",description:"Coaching, observation, échange et apprentissage."},{title:"Intégrité académique",description:"Attentes claires, évaluation équitable et pratiques responsables."}]},
 values:{label:"Nos valeurs en action",title:"Les valeurs comptent lorsqu'elles guident les décisions.",description:"Six principes définissent notre leadership, notre enseignement et notre responsabilité.",items:[{title:"Excellence",description:"Viser de hauts standards et progresser avec soin."},{title:"Intégrité",description:"Agir honnêtement, éthiquement et avec cohérence."},{title:"Respect",description:"Écouter et reconnaître la dignité de chacun."},{title:"Inclusion",description:"Permettre à tous de participer et réussir."},{title:"Collaboration",description:"Partager savoir, responsabilité et résultats."},{title:"Innovation",description:"Améliorer les pratiques de façon responsable."}]},
 cta:{label:"Leadership pour demain",title:"Construire l'avenir ensemble",description:"Découvrez les personnes qui créent une communauté fondée sur la qualité, la responsabilité et l'innovation.",motto:"Excellence en leadership. Excellence en éducation.",actions:["Rencontrer le corps enseignant","Explorer les programmes","Nous joindre"]}
},
zh:{
 hero:{eyebrow:"领导与治理",title:"以学术领导力引领发展",description:"领导团队、学术顾问和教育专业人士共同工作，确保学生体验的每个部分都体现高标准的学术质量、诚信、关怀与责任。",slogans:["学术卓越","战略愿景","学生成功"]},
 governance:{label:"治理理念",title:"强大的机构建立在强有力的治理之上。",description:"治理框架将教育使命与负责任决策连接。明确角色、证据、对话和定期审查使中心保持雄心、透明并始终以学生为中心。",principles:[{title:"学术质量",description:"课程依据明确成果和大学导向标准进行设计、审查和改进。"},{title:"透明度",description:"清晰一致地沟通决策、责任、要求和学生流程。"},{title:"问责制",description:"领导与团队对成果、执行、伦理实践和学生体验负责。"},{title:"持续改进",description:"以数据、反馈、反思和专业学习推动有意义改变。"},{title:"学生中心决策",description:"根据对学习、福祉、机会和未来成功的实际影响评估优先事项。"}]},
 director:{label:"执行董事致辞",title:"教育能够改变人生、拓展机会并产生持久影响。",message:"领导力意味着创造让学生和教育者都能发挥最佳水平的条件。我们将明确学术要求、个性化支持、负责任创新以及对每位学习者潜力的信念结合。",promise:"我们的承诺是帮助学生培养实现目标并积极贡献未来社区所需的知识、技能、信心和品格。",progression:["教育创造机会","机会创造可能","可能创造未来"],signature:"Isabelle Tremblay 博士 · 执行董事"},
 board:{label:"学术顾问委员会",title:"为学术标准、项目质量和教育创新提供战略指导。",description:"委员会汇聚资深教育者、研究者和行业顾问，挑战假设、审视方向，确保课程严谨、相关并持续回应变化。",responsibilities:[{title:"推动学术卓越",description:"制定有雄心的要求并保护学习成果完整性。"},{title:"支持课程开发",description:"审查课程架构、学习进度、评估和衔接。"},{title:"提升教育质量",description:"以证据和外部视角改善教学与学生体验。"},{title:"鼓励创新",description:"探索教学、科技和国际教育的新方法。"},{title:"强化学生成果",description:"持续关注进步、准备度、归属感和长期成就。"}],tags:["学术领导力","教育创新","质量保证","学生成功"]},
 team:{label:"我们的领导团队",title:"覆盖学术、学生成功、国际项目和招生的专业领导。",description:"每个职能拥有明确使命，同时围绕机构质量和学生成功协同工作。",leaders:[{name:"Isabelle Tremblay 博士",role:"执行董事",initials:"IT",bio:"负责战略领导、机构方向、合作关系及中心使命问责。"},{name:"Marc-André Gagnon 博士",role:"学术主任",initials:"MG",bio:"领导课程开发、师资标准、学术质量、评估和教育成果。"},{name:"Sofia Rahman",role:"学生成功主任",initials:"SR",bio:"负责顾问、学生支持、身心健康、参与、迎新和学业进展。"},{name:"David Chen",role:"国际项目主任",initials:"DC",bio:"领导国际招生、机构合作、全球项目和学生流动。"},{name:"Nadia Benali",role:"招生主任",initials:"NB",bio:"负责招生政策、申请审核、注册规划和申请人沟通。"}]},
 faculty:{label:"师资卓越",title:"敬业教育者，卓越学习体验。",description:"教师团队融合学科知识、学术严谨、跨文化意识和对学生发展的深度承诺。",commitments:[{title:"学术严谨",description:"明确标准、有意义评估和大学级要求。"},{title:"学生参与",description:"学生主动提问、讨论、实践、创造并承担责任。"},{title:"包容教学",description:"尊重不同教育背景、语言、优势和学习需求。"},{title:"持续专业发展",description:"持续学习教学、评估、学生支持和科技。"},{title:"教育创新",description:"在真正改善理解、参与和成果时采用新方法。"}],slogans:["以使命教学","激发成就"]},
 quality:{label:"质量保证",title:"通过持续审查和改进循环保护教育质量。",description:"我们关注教了什么、学生学到了什么、课程是否稳定实施，以及体验如何变得更强。",processes:[{title:"课程审查",description:"定期检查相关性、顺序、学习量、成果和衔接。"},{title:"项目评估",description:"分析表现、进步、完成、参与和准备度。"},{title:"学生反馈",description:"结构化评价课程、服务、支持和整体体验。"},{title:"教师发展",description:"教练、观察、同伴交流和专业学习。"},{title:"学术诚信",description:"明确要求、负责任学术、公平评估和一致流程。"}]},
 values:{label:"价值观落地",title:"只有影响日常决定，价值观才真正有意义。",description:"六项共同原则定义我们的领导、教学、协作、学生支持与自我问责。",items:[{title:"卓越",description:"设定高标准，以纪律和用心持续改进。"},{title:"诚信",description:"诚实、透明、合乎伦理并保持一致。"},{title:"尊重",description:"认真倾听并认可他人的尊严、经验和贡献。"},{title:"包容",description:"创造让不同的人都能参与、归属和成功的条件。"},{title:"协作",description:"分享知识、责任、反馈和成果。"},{title:"创新",description:"质疑固有实践，在出现更好可能时负责任地改进。"}]},
 cta:{label:"面向未来的领导力",title:"共同建设未来",description:"认识正在打造高质量、负责任、创新并共同承诺学生成功的学术社区的教育者与领导者。",motto:"卓越领导，卓越教育。",actions:["认识我们的教师","探索课程","联系我们"]}
}}
