import type { Locale } from "@/content/site-content";

type Item = { title: string; description: string };

export type StudentLifeContent = {
  hero: { eyebrow: string; title: string; subtitle: string; description: string; slogans: string[] };
  campus: { label: string; title: string; description: string; items: Item[]; motto: string };
  location: { label: string; title: string; description: string; items: Item[] };
  montreal: { label: string; title: string; description: string; qualities: Item[]; tags: string[] };
  community: { label: string; title: string; description: string; promises: string[] };
  wellbeing: { label: string; title: string; description: string; items: Item[] };
  beyond: { label: string; title: string; description: string; items: Item[] };
  stories: { label: string; title: string; description: string; transformations: string[] };
  visit: { label: string; title: string; description: string; options: Item[] };
  cta: { label: string; title: string; description: string; motto: string[]; actions: string[] };
};

export const studentLifeContent: Record<Locale, StudentLifeContent> = {
  en: {
    hero: { eyebrow: "Student Life & Campus Experience", title: "More Than an Education", subtitle: "A Community. A Campus. A Future.", description: "Education extends far beyond the classroom. At the UdeM Brossard Campus, students combine purposeful academic preparation with friendships, cultural discovery, personal growth, and the energy of Greater Montréal.", slogans: ["Study with Purpose", "Connect with Others", "Build Your Future"] },
    campus: { label: "The UdeM Brossard Campus", title: "A modern university environment designed for active learning.", description: "Contemporary spaces, digital tools, and a welcoming academic atmosphere allow students to participate fully, work together, and experience the rhythm of university life from the first day.", items: [{ title: "Modern classrooms", description: "Flexible teaching spaces support discussion, project work, presentations, and different ways of learning." }, { title: "Digital learning environment", description: "Technology-enabled classrooms connect multimedia instruction, online resources, collaborative tools, and independent study." }, { title: "Academic events", description: "Guest lectures, workshops, conferences, and information sessions bring new ideas and university perspectives into campus life." }, { title: "Collaborative spaces", description: "Dedicated areas give students room to prepare assignments, meet classmates, exchange feedback, and study between classes." }], motto: "Designed for the Future of Learning" },
    location: { label: "The Brossard advantage", title: "Connected to Montréal. Surrounded by everyday possibility.", description: "The campus sits in a fast-growing South Shore district where transportation, services, education, business, and urban development meet.", items: [{ title: "REM rapid transit", description: "The REM connects Brossard directly with Montréal's wider transit network, downtown destinations, universities, and cultural districts." }, { title: "Shopping and services", description: "Restaurants, cafés, retail, banking, groceries, and daily services are available within a convenient and walkable area." }, { title: "Recreation and entertainment", description: "Parks, sports, community facilities, cinemas, events, and gathering spaces support a balanced student lifestyle." }, { title: "Innovation ecosystem", description: "Education, business, technology, and urban development come together in one of Greater Montréal's most dynamic growth areas." }] },
    montreal: { label: "Life in Montréal", title: "One of the world's great student cities.", description: "Montréal combines academic excellence, cultural diversity, economic opportunity, and exceptional quality of life in a city that rewards curiosity.", qualities: [{ title: "Academic excellence", description: "A dense network of universities, colleges, libraries, researchers, and student communities." }, { title: "Cultural diversity", description: "Languages, neighbourhoods, food, music, festivals, arts, and traditions from around the world." }, { title: "Economic opportunity", description: "Growing sectors in AI, technology, aerospace, health sciences, design, finance, and creative industries." }, { title: "Quality of life", description: "Public transit, green space, cultural life, student neighbourhoods, and experiences in every season." }], tags: ["A Global City", "A Bilingual City", "A Safe City", "A City of Opportunity"] },
    community: { label: "International student community", title: "A global learning environment where everyone brings something valuable.", description: "Students from different countries, cultures, languages, and educational systems learn beside one another. That diversity turns everyday conversation, teamwork, and campus life into preparation for an interconnected world.", promises: ["Build International Friendships", "Learn from Different Perspectives", "Develop Global Competencies", "Expand Your International Network"] },
    wellbeing: { label: "Student support & wellbeing", title: "Success includes academic progress, personal wellbeing, and belonging.", description: "Support is designed around the whole student experience, helping learners ask for assistance early, stay healthy, and participate confidently.", items: [{ title: "Academic support", description: "Advising, tutoring, writing guidance, learning strategies, progress conversations, and academic coaching." }, { title: "Student services", description: "Practical help with housing information, transportation, insurance, documentation, and daily life in Canada." }, { title: "Orientation programs", description: "Pre-arrival information and first-week activities introduce campus systems, expectations, classmates, and Canadian culture." }, { title: "Community engagement", description: "Clubs, peer activities, volunteer opportunities, and group events help students participate and form meaningful connections." }, { title: "Wellness & balance", description: "Information, referrals, healthy routines, recreational opportunities, and a culture that encourages students to seek support." }] },
    beyond: { label: "Learning beyond the classroom", title: "Experience turns knowledge into confidence.", description: "Co-curricular activities help students practise communication, leadership, collaboration, creativity, and professional behaviour in new settings.", items: [{ title: "Academic workshops", description: "Focused sessions on research, writing, presentation, study strategy, academic integrity, and university planning." }, { title: "Leadership programs", description: "Opportunities to organize, mentor, facilitate, represent peers, and take responsibility within a team." }, { title: "Cultural activities", description: "Museum visits, festivals, neighbourhood exploration, language exchange, and shared celebrations across cultures." }, { title: "Community engagement", description: "Volunteer, service-learning, and local partnership activities connect learning with people and place." }, { title: "Professional development", description: "Career conversations, workplace communication, networking, résumé preparation, and internship readiness." }] },
    stories: { label: "Student success stories", title: "Every journey begins in one place—and grows beyond it.", description: "Success looks different for every student. The Center creates the conditions for learners to recognize progress, take ownership of their development, and imagine what comes next.", transformations: ["From Language Learning to Academic Confidence", "From Newcomer to University Student", "From Potential to Achievement", "From Ambition to Success"] },
    visit: { label: "Experience the campus", title: "See where your next chapter could begin.", description: "Prospective students and families are invited to discover the Brossard Campus, explore the learning environment, and speak directly with the people who support the student journey.", options: [{ title: "Campus tour", description: "Walk through teaching and collaborative spaces, understand the location, and experience the atmosphere in person." }, { title: "Virtual information session", description: "Meet online for an overview of programs, admissions, tuition, student services, and life in Greater Montréal." }, { title: "Advisor consultation", description: "Discuss academic background, language level, future goals, and the pathway that best fits the student's plans." }] },
    cta: { label: "Join our community", title: "A Place to Learn. A Place to Belong.", description: "Gain more than academic preparation. Join a community that values excellence, diversity, inclusion, curiosity, and the confidence to build a future.", motto: ["Learn", "Grow", "Belong"], actions: ["Book a Campus Tour", "Request Information", "Apply Now"] },
  },
  fr: {
    hero: { eyebrow: "Vie étudiante et expérience de campus", title: "Bien plus qu'une formation", subtitle: "Une communauté. Un campus. Un avenir.", description: "L'éducation dépasse la salle de classe. Au campus UdeM de Brossard, les étudiants réunissent préparation académique, amitiés, découverte culturelle, croissance personnelle et énergie montréalaise.", slogans: ["Étudier avec intention", "Créer des liens", "Construire son avenir"] },
    campus: { label: "Le campus UdeM de Brossard", title: "Un milieu universitaire moderne conçu pour l'apprentissage actif.", description: "Des espaces contemporains, des outils numériques et une atmosphère accueillante permettent de participer, collaborer et vivre le rythme universitaire dès le premier jour.", items: [{ title: "Salles modernes", description: "Des espaces flexibles pour la discussion, les projets, les présentations et différentes façons d'apprendre." }, { title: "Milieu numérique", description: "Classes technologiques, multimédia, ressources en ligne, outils collaboratifs et étude autonome." }, { title: "Activités académiques", description: "Conférences, ateliers, colloques et séances d'information font entrer de nouvelles idées sur le campus." }, { title: "Espaces collaboratifs", description: "Des lieux pour préparer les travaux, rencontrer les collègues, échanger et étudier entre les cours." }], motto: "Conçu pour l'avenir de l'apprentissage" },
    location: { label: "L'avantage Brossard", title: "Relié à Montréal, entouré de possibilités.", description: "Le campus se trouve dans un secteur de la Rive-Sud où transport, services, éducation, affaires et développement urbain se rencontrent.", items: [{ title: "Réseau express métropolitain", description: "Le REM relie directement Brossard au réseau montréalais, au centre-ville, aux universités et aux quartiers culturels." }, { title: "Commerces et services", description: "Restaurants, cafés, commerces, banques, épiceries et services quotidiens se trouvent à proximité." }, { title: "Loisirs et divertissement", description: "Parcs, sports, installations communautaires, cinéma et événements soutiennent une vie équilibrée." }, { title: "Écosystème d'innovation", description: "Éducation, entreprises, technologie et développement urbain convergent dans un secteur dynamique." }] },
    montreal: { label: "Vivre à Montréal", title: "L'une des grandes villes étudiantes du monde.", description: "Montréal combine excellence académique, diversité culturelle, possibilités économiques et qualité de vie.", qualities: [{ title: "Excellence académique", description: "Un réseau dense d'universités, collèges, bibliothèques, chercheurs et communautés étudiantes." }, { title: "Diversité culturelle", description: "Langues, quartiers, cuisine, musique, festivals, arts et traditions du monde entier." }, { title: "Possibilités économiques", description: "IA, technologie, aérospatiale, santé, design, finance et industries créatives." }, { title: "Qualité de vie", description: "Transport, espaces verts, culture, quartiers étudiants et expériences en toute saison." }], tags: ["Ville mondiale", "Ville bilingue", "Ville sécuritaire", "Ville de possibilités"] },
    community: { label: "Communauté étudiante internationale", title: "Un milieu mondial où chacun apporte quelque chose d'unique.", description: "Des étudiants de pays, cultures, langues et systèmes éducatifs différents apprennent ensemble. Cette diversité prépare à un monde interconnecté.", promises: ["Créer des amitiés internationales", "Apprendre de perspectives différentes", "Développer des compétences mondiales", "Élargir son réseau international"] },
    wellbeing: { label: "Soutien et bien-être", title: "La réussite comprend progrès, bien-être et sentiment d'appartenance.", description: "Le soutien englobe toute l'expérience étudiante pour aider chacun à demander de l'aide, rester en santé et participer avec confiance.", items: [{ title: "Soutien académique", description: "Conseils, tutorat, rédaction, stratégies, suivi des progrès et coaching." }, { title: "Services aux étudiants", description: "Logement, transport, assurance, documents et vie quotidienne au Canada." }, { title: "Programmes d'accueil", description: "Information avant l'arrivée et activités présentant le campus, les attentes et la culture canadienne." }, { title: "Engagement communautaire", description: "Clubs, activités entre pairs, bénévolat et événements pour créer des liens." }, { title: "Bien-être et équilibre", description: "Ressources, références, habitudes saines, loisirs et culture de soutien." }] },
    beyond: { label: "Apprendre au-delà de la classe", title: "L'expérience transforme les connaissances en confiance.", description: "Les activités permettent de pratiquer communication, leadership, collaboration, créativité et professionnalisme.", items: [{ title: "Ateliers académiques", description: "Recherche, rédaction, présentation, stratégies, intégrité et planification universitaire." }, { title: "Programmes de leadership", description: "Organiser, encadrer, faciliter, représenter les pairs et prendre des responsabilités." }, { title: "Activités culturelles", description: "Musées, festivals, quartiers, échanges linguistiques et célébrations." }, { title: "Engagement communautaire", description: "Bénévolat, apprentissage par le service et partenariats locaux." }, { title: "Développement professionnel", description: "Carrière, communication, réseautage, CV et préparation aux stages." }] },
    stories: { label: "Histoires de réussite", title: "Chaque parcours commence quelque part et grandit au-delà.", description: "La réussite prend une forme différente pour chacun. Le Centre aide les étudiants à reconnaître leurs progrès et à imaginer la suite.", transformations: ["Des langues à la confiance académique", "De nouvel arrivant à étudiant universitaire", "Du potentiel à la réalisation", "De l'ambition à la réussite"] },
    visit: { label: "Découvrez le campus", title: "Voyez où votre prochain chapitre peut commencer.", description: "Les futurs étudiants et leurs familles peuvent explorer le campus et rencontrer les personnes qui soutiennent le parcours.", options: [{ title: "Visite du campus", description: "Découvrir les espaces, comprendre l'emplacement et ressentir l'atmosphère en personne." }, { title: "Séance virtuelle", description: "Programmes, admission, droits, services et vie dans le Grand Montréal." }, { title: "Consultation", description: "Discuter du parcours scolaire, du niveau linguistique, des objectifs et du programme adapté." }] },
    cta: { label: "Rejoignez notre communauté", title: "Un lieu pour apprendre. Un lieu d'appartenance.", description: "Gagnez plus qu'une préparation académique : rejoignez une communauté qui valorise excellence, diversité et confiance.", motto: ["Apprendre", "Grandir", "Appartenir"], actions: ["Réserver une visite", "Demander de l'information", "Faire une demande"] },
  },
  zh: {
    hero: { eyebrow: "学生生活与校园体验", title: "学习之外，也在这里找到归属。", subtitle: "一座校园，一个社区，一段新的开始。", description: "教育不只发生在课堂。在蒙大 Brossard 校区，学生将在学术准备、国际友谊、文化探索、个人成长与蒙特利尔城市生活之间，建立属于自己的节奏。", slogans: ["带着目标学习", "在交流中成长", "为未来积蓄力量"] },
    campus: { label: "蒙大 Brossard 校区", title: "为主动学习而设计的现代大学环境。", description: "现代空间、数字工具与开放的学术氛围，让学生从第一天起参与讨论、开展合作，并逐渐熟悉大学生活的真实节奏。", items: [{ title: "现代化教室", description: "灵活教学空间支持讨论、项目、演讲和多样化学习方式。" }, { title: "数字化学习环境", description: "科技教室连接多媒体教学、在线资源、协作工具和自主学习。" }, { title: "学术活动", description: "讲座、工作坊、会议和说明会把新的思想与大学视野带入校园。" }, { title: "协作空间", description: "学生可以准备作业、交流想法、交换反馈，并在课间专注学习。" }], motto: "为未来学习方式而设计" },
    location: { label: "Brossard 区位优势", title: "连接蒙特利尔，也连接更丰富的日常。", description: "校园位于快速发展的南岸区域，交通、服务、教育、商业、科技与城市发展在这里交汇。", items: [{ title: "REM 快速轨道交通", description: "REM 将 Brossard 与蒙特利尔交通网、市中心、大学及文化区域直接连接。" }, { title: "购物与日常服务", description: "餐厅、咖啡馆、零售、银行、超市和生活服务都在便捷可达的范围内。" }, { title: "休闲娱乐", description: "公园、体育、社区设施、影院、活动与社交空间支持平衡的学生生活。" }, { title: "创新生态区", description: "教育、商业、科技与城市发展共同塑造大蒙特利尔最具活力的增长区域之一。" }] },
    montreal: { label: "蒙特利尔城市生活", title: "世界级学生城市之一。", description: "蒙特利尔将学术卓越、文化多元、经济机会和高品质生活汇聚在一座鼓励探索的城市。", qualities: [{ title: "学术卓越", description: "密集的大学、学院、图书馆、研究者和学生社区网络。" }, { title: "文化多元", description: "来自全球的语言、社区、美食、音乐、节庆、艺术和传统。" }, { title: "经济机会", description: "人工智能、科技、航空、健康科学、设计、金融和创意产业持续发展。" }, { title: "高品质生活", description: "公共交通、绿地、文化、学生社区以及四季都有的丰富体验。" }], tags: ["全球城市", "双语城市", "安全城市", "机遇之城"] },
    community: { label: "国际学生社群", title: "在多元环境中学习，也在差异中拓展视野。", description: "来自不同国家、文化、语言和教育体系的学生共同学习。日常交流、团队合作和校园生活，都成为面向全球化世界的真实准备。", promises: ["建立国际友谊", "理解多元视角", "培养全球能力", "拓展国际人脉"] },
    wellbeing: { label: "学生支持与身心健康", title: "真正的成功，也包括健康、稳定与归属感。", description: "支持体系围绕完整学生体验设计，帮助学生及早获得帮助、保持良好状态，并更自信地参与校园生活。", items: [{ title: "学术支持", description: "学术咨询、辅导、写作指导、学习策略、进度沟通和学业教练。" }, { title: "学生服务", description: "住房信息、交通、保险、文件及加拿大日常生活实际支持。" }, { title: "迎新项目", description: "行前信息和第一周活动介绍校园系统、学习要求、同学及加拿大文化。" }, { title: "社区参与", description: "社团、同伴活动、志愿机会和集体活动帮助学生建立有意义的连接。" }, { title: "身心健康与平衡", description: "资源转介、健康习惯、休闲机会以及鼓励学生寻求支持的校园文化。" }] },
    beyond: { label: "课堂外的学习", title: "体验，会把知识变成真正的信心。", description: "课外活动帮助学生在新环境中练习沟通、领导、协作、创造力和专业行为。", items: [{ title: "学术工作坊", description: "研究、写作、演讲、学习策略、学术诚信和大学规划。" }, { title: "领导力项目", description: "组织活动、指导同伴、主持讨论、代表学生并承担团队责任。" }, { title: "文化活动", description: "博物馆、节庆、社区探索、语言交流和跨文化共同庆祝。" }, { title: "社区参与活动", description: "志愿服务、服务学习和本地合作将学习与人和城市连接。" }, { title: "职业发展机会", description: "职业交流、职场沟通、人脉建立、简历准备和实习能力。" }] },
    stories: { label: "学生成长故事", title: "每一段成长，都从勇敢迈出第一步开始。", description: "成功对每位学生都有不同含义。中心帮助学习者看见自己的进步，掌握成长节奏，并逐渐想象更远的可能。", transformations: ["从语言学习到学术信心", "从初到加拿大到融入大学生活", "从潜力积累到真实成就", "从理想到更清晰的未来"] },
    visit: { label: "体验校园", title: "亲眼看看，下一段旅程可以从哪里开始。", description: "我们邀请预申请学生及家长了解 Brossard 校园、探索学习环境，并直接认识支持学生成长的团队。", options: [{ title: "校园参观", description: "走进教学与协作空间、了解区位，并亲身感受校园氛围。" }, { title: "线上说明会", description: "在线了解课程、招生、学费、学生服务及大蒙特利尔生活。" }, { title: "顾问咨询", description: "讨论学术背景、语言水平、未来目标以及最适合的学习路径。" }] },
    cta: { label: "加入我们的社区", title: "在这里学习，也在这里找到归属。", description: "收获的不只是学术准备，更是一段关于卓越、多元、包容、好奇心与未来信心的成长体验。", motto: ["学习", "成长", "归属"], actions: ["预约校园参观", "索取资料", "立即申请"] },
  },
};
