import type { Locale } from "@/content/site-content";

type Item = { title: string; description: string };

export type WhyUdemContent = {
  hero: { eyebrow: string; title: string; description: string; highlights: string[] };
  recognition: { label: string; title: string; description: string; pillars: Item[] };
  ecosystem: { label: string; title: string; description: string; disciplines: Array<{ name: string; detail: string }> };
  city: { label: string; title: string; description: string; features: Item[] };
  bilingual: { label: string; title: string; description: string; french: string; english: string; lifelong: string };
  research: { label: string; title: string; description: string; words: Array<{ word: string; detail: string }> };
  community: { label: string; title: string; description: string; items: Item[] };
  beyond: { label: string; title: string; description: string; skills: Item[] };
  journey: { label: string; title: string; description: string; paths: Item[] };
  cta: { label: string; title: string; description: string; motto: string[]; actions: string[] };
};

export const whyUdemContent: Record<Locale, WhyUdemContent> = {
  en: {
    hero: { eyebrow: "Why Université de Montréal", title: "A World of Opportunity Begins Here", description: "For more than a century, Université de Montréal has helped shape knowledge, research, and public life in Québec and beyond. As one of the world's largest French-language university communities, it offers an ambitious academic environment in the heart of multicultural Montréal.", highlights: ["A century of academic tradition", "A leading French-language university", "A global city for students"] },
    recognition: { label: "A university of global recognition", title: "An academic community with international reach.", description: "Université de Montréal is known for the scale of its scholarship, the vitality of its research culture, and its ability to attract students, professors, and collaborators from around the world. Its French-language identity is paired with a distinctly international outlook.", pillars: [{ title: "International academic reputation", description: "A comprehensive institution recognized across disciplines for rigorous education, research, and knowledge creation." }, { title: "Global talent", description: "Students and faculty bring different languages, scholarly traditions, professional experience, and perspectives into the same learning community." }, { title: "Research-led learning", description: "Teaching is informed by active inquiry, current scholarship, and the questions shaping society, technology, health, and culture." }, { title: "Future-focused education", description: "Academic depth is connected to innovation, professional preparation, public service, and the ability to lead change." }] },
    ecosystem: { label: "A comprehensive academic ecosystem", title: "Explore ideas across disciplines without limits.", description: "A broad academic environment allows students to understand their chosen field while seeing how it connects to technology, society, health, policy, culture, and the wider world.", disciplines: [{ name: "Business & Management", detail: "Strategy, organizations, finance, markets, and entrepreneurship" }, { name: "Computer Science", detail: "Software, systems, algorithms, and computational thinking" }, { name: "Engineering", detail: "Design, systems, infrastructure, and applied problem solving" }, { name: "Artificial Intelligence", detail: "Machine learning, intelligent systems, ethics, and applications" }, { name: "Data Science", detail: "Statistics, modelling, visualization, and evidence-based decisions" }, { name: "Health Sciences", detail: "Human health, clinical knowledge, population wellbeing, and discovery" }, { name: "Social Sciences", detail: "People, institutions, behaviour, communities, and public life" }, { name: "Education", detail: "Learning, pedagogy, curriculum, inclusion, and leadership" }, { name: "Law", detail: "Legal systems, rights, policy, institutions, and justice" }, { name: "Arts & Humanities", detail: "Languages, history, ideas, creativity, identity, and culture" }] },
    city: { label: "Study in one of the world's great student cities", title: "Montréal brings education, culture, and possibility together.", description: "The city combines the energy of North American innovation with a strong European cultural heritage, international diversity, and a quality of life that helps students learn, connect, and grow.", features: [{ title: "North American innovation", description: "A major environment for research, technology, entrepreneurship, design, and creative industries." }, { title: "European cultural heritage", description: "Historic neighbourhoods, architecture, festivals, food, and arts give Montréal a distinctive rhythm and identity." }, { title: "International diversity", description: "Communities from around the world make global perspectives part of everyday life." }, { title: "Exceptional quality of life", description: "Public transit, parks, cultural life, student neighbourhoods, and four distinct seasons create a balanced experience." }] },
    bilingual: { label: "The advantage of bilingualism", title: "Learn in two global languages. Think beyond one world.", description: "Montréal gives students the uncommon opportunity to develop French and English through study, daily life, collaboration, and professional experience.", french: "French supports meaningful participation in Québec's academic, social, cultural, and professional life.", english: "English connects students with global research, international business, technology, and cross-border opportunity.", lifelong: "Bilingual confidence strengthens communication, cultural intelligence, mobility, and long-term career versatility." },
    research: { label: "Research, innovation & discovery", title: "Where questions become knowledge—and knowledge becomes impact.", description: "Research is not separate from university life. It creates a culture in which students learn to question assumptions, test ideas, work across disciplines, and imagine better responses to complex challenges.", words: [{ word: "Discover", detail: "Observe closely, ask stronger questions, and uncover new possibilities." }, { word: "Innovate", detail: "Transform insight into methods, systems, services, and solutions." }, { word: "Create", detail: "Connect knowledge with imagination, design, and meaningful expression." }, { word: "Lead", detail: "Use evidence, responsibility, and collaboration to move ideas forward." }] },
    community: { label: "A global community", title: "Learn alongside people who expand your view of the world.", description: "Students join a multilingual, multicultural academic community in which difference becomes a source of learning, connection, and shared ambition.", items: [{ title: "Cross-cultural collaboration", description: "Work with classmates whose experiences and approaches challenge familiar assumptions." }, { title: "Global networking", description: "Build relationships across disciplines, countries, industries, and future professional fields." }, { title: "International perspectives", description: "Understand how the same challenge can be interpreted differently across communities and systems." }, { title: "Lifelong friendships", description: "Create bonds through classes, campus life, shared projects, and the experience of living in Montréal." }] },
    beyond: { label: "Student success beyond the classroom", title: "University develops the person as well as the scholar.", description: "Academic knowledge becomes more powerful when students can communicate it, apply it, and use it responsibly with others.", skills: [{ title: "Leadership", description: "Take initiative, set direction, listen well, and help teams move toward shared goals." }, { title: "Professional communication", description: "Write, present, negotiate, and adapt messages for academic and professional audiences." }, { title: "Problem solving", description: "Frame complex challenges, evaluate options, and make informed decisions under uncertainty." }, { title: "Team collaboration", description: "Contribute reliably, manage difference, exchange feedback, and share responsibility for results." }, { title: "Global awareness", description: "Connect local choices to wider cultural, social, economic, and environmental realities." }] },
    journey: { label: "Your journey to success", title: "Many ambitions. A university environment built to support them.", description: "Whether students are beginning a first degree or imagining a global career, the university journey can open several connected directions for achievement.", paths: [{ title: "Undergraduate studies", description: "Build disciplinary knowledge, academic confidence, and a strong foundation for future options." }, { title: "Graduate education", description: "Deepen expertise through advanced coursework, professional study, or specialized research." }, { title: "Research excellence", description: "Contribute to new knowledge through inquiry, laboratories, fieldwork, analysis, and scholarly collaboration." }, { title: "Professional success", description: "Translate academic learning into judgment, communication, technical capability, and career readiness." }, { title: "International careers", description: "Use bilingual ability, global awareness, and a diverse network to work across borders and cultures." }] },
    cta: { label: "Begin your future today", title: "Join a community of excellence.", description: "Take the first step toward a university future shaped by academic depth, research, bilingual opportunity, and international connection.", motto: ["Excellence", "Innovation", "Opportunity"], actions: ["Apply Now", "Book a Consultation", "Contact Us"] },
  },
  fr: {
    hero: { eyebrow: "Pourquoi l'Université de Montréal", title: "Un monde de possibilités commence ici", description: "Depuis plus d'un siècle, l'Université de Montréal contribue au savoir, à la recherche et à la vie publique au Québec et ailleurs. L'une des plus grandes communautés universitaires francophones au monde offre un milieu ambitieux au cœur d'une métropole multiculturelle.", highlights: ["Un siècle de tradition académique", "Une grande université francophone", "Une ville étudiante mondiale"] },
    recognition: { label: "Une université reconnue mondialement", title: "Une communauté académique d'envergure internationale.", description: "L'Université de Montréal se distingue par l'ampleur de son savoir, sa culture de recherche et sa capacité à attirer étudiants, professeurs et partenaires du monde entier.", pillars: [{ title: "Réputation académique", description: "Une institution complète reconnue pour la rigueur de son enseignement, de sa recherche et de sa création de connaissances." }, { title: "Talents du monde entier", description: "Étudiants et professeurs réunissent langues, traditions savantes, expériences et perspectives." }, { title: "Apprentissage par la recherche", description: "L'enseignement s'appuie sur la recherche actuelle et les questions qui façonnent la société." }, { title: "Formation tournée vers l'avenir", description: "La profondeur académique rejoint innovation, préparation professionnelle et service public." }] },
    ecosystem: { label: "Un écosystème académique complet", title: "Explorer les idées entre disciplines, sans limites.", description: "Un vaste milieu permet de comprendre son domaine et ses liens avec la technologie, la société, la santé, les politiques et la culture.", disciplines: [{ name: "Gestion", detail: "Stratégie, organisations, finance, marchés et entrepreneuriat" }, { name: "Informatique", detail: "Logiciels, systèmes, algorithmes et pensée informatique" }, { name: "Génie", detail: "Conception, systèmes, infrastructures et solutions appliquées" }, { name: "Intelligence artificielle", detail: "Apprentissage automatique, systèmes intelligents et éthique" }, { name: "Science des données", detail: "Statistiques, modèles, visualisation et décisions" }, { name: "Sciences de la santé", detail: "Santé humaine, clinique, populations et découverte" }, { name: "Sciences sociales", detail: "Personnes, institutions, comportements et communautés" }, { name: "Éducation", detail: "Apprentissage, pédagogie, programmes, inclusion et direction" }, { name: "Droit", detail: "Systèmes juridiques, droits, politiques et justice" }, { name: "Arts et lettres", detail: "Langues, histoire, idées, créativité et culture" }] },
    city: { label: "Étudier dans une grande ville étudiante", title: "Montréal réunit éducation, culture et possibilités.", description: "La ville associe l'innovation nord-américaine, un héritage culturel européen, une diversité internationale et une qualité de vie propice aux études.", features: [{ title: "Innovation nord-américaine", description: "Un milieu majeur pour la recherche, la technologie, l'entrepreneuriat et les industries créatives." }, { title: "Héritage culturel européen", description: "Quartiers historiques, architecture, festivals, cuisine et arts donnent à Montréal son identité." }, { title: "Diversité internationale", description: "Des communautés du monde entier font des perspectives mondiales une réalité quotidienne." }, { title: "Qualité de vie", description: "Transport, parcs, culture, quartiers étudiants et quatre saisons créent un milieu équilibré." }] },
    bilingual: { label: "L'avantage du bilinguisme", title: "Apprendre dans deux langues mondiales.", description: "Montréal permet de développer français et anglais par les études, la vie quotidienne, la collaboration et l'expérience professionnelle.", french: "Le français ouvre la participation à la vie académique, sociale, culturelle et professionnelle du Québec.", english: "L'anglais relie la recherche mondiale, les affaires internationales, la technologie et les possibilités transfrontalières.", lifelong: "La confiance bilingue renforce communication, intelligence culturelle, mobilité et polyvalence professionnelle." },
    research: { label: "Recherche, innovation et découverte", title: "Quand les questions deviennent savoir et le savoir devient impact.", description: "La recherche crée une culture où l'on remet en question les idées, teste des solutions et travaille entre disciplines.", words: [{ word: "Découvrir", detail: "Observer, poser de meilleures questions et révéler de nouvelles possibilités." }, { word: "Innover", detail: "Transformer les idées en méthodes, systèmes, services et solutions." }, { word: "Créer", detail: "Relier connaissance, imagination, design et expression." }, { word: "Diriger", detail: "Faire avancer les idées par les preuves, la responsabilité et la collaboration." }] },
    community: { label: "Une communauté mondiale", title: "Apprendre avec des personnes qui élargissent votre vision.", description: "Une communauté multilingue et multiculturelle où la différence nourrit l'apprentissage et l'ambition partagée.", items: [{ title: "Collaboration interculturelle", description: "Travailler avec des personnes dont les expériences remettent en question les habitudes." }, { title: "Réseau mondial", description: "Créer des liens entre disciplines, pays, industries et professions." }, { title: "Perspectives internationales", description: "Comprendre comment un même défi varie selon les communautés et systèmes." }, { title: "Amitiés durables", description: "Créer des liens grâce aux cours, à la vie de campus et à Montréal." }] },
    beyond: { label: "La réussite au-delà de la classe", title: "L'université forme la personne autant que le spécialiste.", description: "Le savoir devient plus puissant lorsqu'on sait le communiquer, l'appliquer et l'utiliser avec responsabilité.", skills: [{ title: "Leadership", description: "Prendre l'initiative, écouter et aider une équipe à atteindre un but commun." }, { title: "Communication professionnelle", description: "Rédiger, présenter, négocier et adapter son message." }, { title: "Résolution de problèmes", description: "Définir les défis, évaluer les options et décider avec discernement." }, { title: "Travail d'équipe", description: "Contribuer, gérer les différences, partager la rétroaction et la responsabilité." }, { title: "Conscience mondiale", description: "Relier les décisions locales aux réalités culturelles, sociales et environnementales." }] },
    journey: { label: "Votre parcours vers la réussite", title: "Plusieurs ambitions, un milieu pour les soutenir.", description: "Du premier diplôme à une carrière mondiale, le parcours universitaire ouvre plusieurs directions complémentaires.", paths: [{ title: "Premier cycle", description: "Construire connaissances disciplinaires, confiance et fondations durables." }, { title: "Cycles supérieurs", description: "Approfondir son expertise par des cours avancés, une formation professionnelle ou la recherche." }, { title: "Excellence en recherche", description: "Contribuer au savoir par l'enquête, les laboratoires, le terrain et la collaboration." }, { title: "Réussite professionnelle", description: "Transformer les études en jugement, communication, compétences et préparation de carrière." }, { title: "Carrières internationales", description: "Mobiliser bilinguisme, ouverture mondiale et réseau diversifié au-delà des frontières." }] },
    cta: { label: "Commencez votre avenir aujourd'hui", title: "Rejoignez une communauté d'excellence.", description: "Faites le premier pas vers un avenir façonné par la profondeur académique, la recherche, le bilinguisme et les liens internationaux.", motto: ["Excellence", "Innovation", "Possibilités"], actions: ["Faire une demande", "Réserver une consultation", "Nous joindre"] },
  },
  zh: {
    hero: { eyebrow: "为什么选择蒙特利尔大学", title: "在这里，看见更广阔的学术机会。", description: "一个多世纪以来，蒙特利尔大学持续影响魁北克乃至更广阔世界的知识、研究与公共生活。作为全球规模领先的法语大学社区之一，它在多元文化城市蒙特利尔提供充满雄心的学术环境。", highlights: ["百年学术传统", "领先的法语大学", "世界级学生城市"] },
    recognition: { label: "全球认可的大学", title: "拥有国际影响力的学术共同体。", description: "蒙特利尔大学以广泛的学术规模、活跃的研究文化以及吸引全球学生、教授和合作伙伴的能力而闻名。法语大学身份与鲜明的国际视野在这里并行。", pillars: [{ title: "国际学术声誉", description: "综合性学术机构，以严谨教育、研究实力和知识创造获得广泛认可。" }, { title: "汇聚全球人才", description: "学生与教师带来不同语言、学术传统、专业经验和世界观点。" }, { title: "研究引领学习", description: "教学连接正在发生的研究，以及塑造社会、科技、健康和文化的重要问题。" }, { title: "面向未来的教育", description: "将学术深度与创新、职业准备、公共服务和领导变革的能力连接。" }] },
    ecosystem: { label: "综合学术生态", title: "跨越学科边界，探索无限思想。", description: "广泛的学术环境让学生深入理解所选领域，同时看见它与科技、社会、健康、政策、文化及世界的联系。", disciplines: [{ name: "商科与管理", detail: "战略、组织、金融、市场与创业" }, { name: "计算机科学", detail: "软件、系统、算法与计算思维" }, { name: "工程", detail: "设计、系统、基础设施与应用解决方案" }, { name: "人工智能", detail: "机器学习、智能系统、伦理与应用" }, { name: "数据科学", detail: "统计、建模、可视化与循证决策" }, { name: "健康科学", detail: "人类健康、临床知识、群体福祉与发现" }, { name: "社会科学", detail: "人、制度、行为、社区与公共生活" }, { name: "教育学", detail: "学习、教学、课程、包容与领导" }, { name: "法学", detail: "法律体系、权利、政策、制度与正义" }, { name: "人文与艺术", detail: "语言、历史、思想、创造、身份与文化" }] },
    city: { label: "在世界级学生城市学习", title: "蒙特利尔让教育、文化与可能性相遇。", description: "这座城市融合北美创新活力、欧洲文化底蕴、国际多元社区和高品质生活，帮助学生学习、连接并成长。", features: [{ title: "北美创新", description: "研究、科技、创业、设计和创意产业的重要环境。" }, { title: "欧洲文化底蕴", description: "历史街区、建筑、节庆、美食与艺术赋予城市独特节奏。" }, { title: "国际多元", description: "来自世界各地的社区让全球视野自然成为日常生活的一部分。" }, { title: "高品质生活", description: "公共交通、公园、文化、学生社区和四季体验共同创造平衡生活。" }] },
    bilingual: { label: "双语优势", title: "学习两种全球语言，理解不止一个世界。", description: "蒙特利尔为学生提供难得机会，在学习、日常生活、合作与职业体验中同步发展法语和英语。", french: "法语帮助学生真正参与魁北克的学术、社会、文化和职业生活。", english: "英语连接全球研究、国际商业、科技发展和跨国机会。", lifelong: "双语信心持续增强沟通、文化理解、国际流动性和长期职业适应力。" },
    research: { label: "研究、创新与发现", title: "让问题成为知识，让知识产生影响。", description: "研究并非大学生活之外的独立活动，而是一种鼓励质疑假设、验证观点、跨学科协作并回应复杂挑战的文化。", words: [{ word: "发现", detail: "细致观察、提出更好的问题并看见新的可能。" }, { word: "创新", detail: "将洞见转化为方法、系统、服务与解决方案。" }, { word: "创造", detail: "连接知识、想象力、设计与有意义的表达。" }, { word: "引领", detail: "以证据、责任与协作推动观点向前。" }] },
    community: { label: "全球社区", title: "与不断拓宽你世界视野的人共同学习。", description: "学生加入一个多语言、多文化的学术社区，让差异成为学习、连接和共同理想的来源。", items: [{ title: "跨文化协作", description: "与经历和思考方式不同的同学合作，挑战熟悉的假设。" }, { title: "全球人脉", description: "建立跨学科、跨国家、跨行业及未来职业领域的关系。" }, { title: "国际视野", description: "理解同一挑战在不同社区和体系中可能拥有不同解释。" }, { title: "终身友谊", description: "通过课堂、校园生活、共同项目及蒙特利尔体验建立深厚连接。" }] },
    beyond: { label: "课堂之外的学生成功", title: "大学既培养学者，也塑造完整的人。", description: "当学生能够清晰沟通、实际应用并与他人负责任地协作时，学术知识才会产生更强力量。", skills: [{ title: "领导力", description: "主动承担责任、明确方向、善于倾听并推动团队实现共同目标。" }, { title: "专业沟通", description: "面向学术和职业受众进行写作、展示、协商并调整表达方式。" }, { title: "解决问题", description: "界定复杂挑战、评估选择并在不确定环境中作出有依据的决定。" }, { title: "团队协作", description: "可靠贡献、处理差异、交换反馈并共同承担结果。" }, { title: "全球意识", description: "将本地选择与更广泛的文化、社会、经济和环境现实连接。" }] },
    journey: { label: "你的成功之路", title: "多种理想，一个能够支持它们的大学环境。", description: "无论学生正在开始第一个学位，还是规划国际职业，大学旅程都能开启多条相互连接的发展方向。", paths: [{ title: "本科阶段", description: "建立专业知识、学术信心，并为未来选择打下坚实基础。" }, { title: "研究生教育", description: "通过高级课程、专业学习或专项研究深化能力。" }, { title: "科研卓越", description: "通过探究、实验、田野、分析与学术合作贡献新知识。" }, { title: "职业成功", description: "将学术学习转化为判断、沟通、技术能力和职业准备。" }, { title: "国际职业", description: "运用双语能力、全球意识和多元网络，在跨境与跨文化环境中发展。" }] },
    cta: { label: "今天开启你的未来", title: "加入追求卓越的学术社区。", description: "迈出第一步，走向一个由学术深度、研究创新、双语机会与国际连接共同塑造的大学未来。", motto: ["卓越", "创新", "机遇"], actions: ["立即申请", "预约咨询", "联系我们"] },
  },
};
