import type { Locale } from "@/content/site-content";

type Item = { title: string; description: string };
export type WhyMontrealContent = {
  hero: { eyebrow: string; title: string; subtitle: string; description: string; slogans: string[] };
  destination: { label: string; title: string; description: string; items: Item[]; tags: string[] };
  bilingual: { label: string; title: string; description: string; benefits: Item[]; statements: string[] };
  welcome: { label: string; title: string; description: string; tags: string[]; quote: string };
  innovation: { label: string; title: string; description: string; sectors: Item[]; slogans: string[] };
  culture: { label: string; title: string; description: string; experiences: Item[] };
  career: { label: string; title: string; description: string; ecosystem: Item[]; slogans: string[] };
  studentLife: { label: string; title: string; description: string; items: Item[] };
  citizens: { label: string; title: string; description: string; qualities: Item[]; slogans: string[] };
  cta: { label: string; title: string; description: string; motto: string; actions: string[] };
};

export const whyMontrealContent: Record<Locale, WhyMontrealContent> = {
  en: {
    hero: { eyebrow: "Why Montréal", title: "Why Study in Montréal?", subtitle: "A City Where Education, Innovation, and Opportunity Meet", description: "Choosing a university matters. Choosing the city where you will live, learn, and grow matters just as much. Montréal combines academic excellence, cultural diversity, economic opportunity, and an exceptional quality of life in one distinctly international student city.", slogans: ["Study in a Global City", "Build an International Future", "Experience Life Without Limits"] },
    destination: { label: "A global education destination", title: "A city built for students, ideas, and discovery.", description: "Every year, Montréal welcomes learners from Canada and around the world into an environment shaped by universities, research, creativity, and open exchange.", items: [{ title: "World-class education", description: "A dense network of universities, colleges, libraries, laboratories, and academic communities." }, { title: "International diversity", description: "Students encounter languages, cultures, traditions, and perspectives from every part of the world." }, { title: "Affordable student living", description: "Compared with many major North American study destinations, Montréal offers strong value in housing, transit, food, and cultural life." }, { title: "Career opportunity", description: "Students connect with high-growth industries, employers, researchers, entrepreneurs, and professional networks." }, { title: "Vibrant culture", description: "Festivals, arts, music, food, sport, and neighbourhood life make learning beyond campus part of everyday experience." }], tags: ["A City of Learning", "A City of Discovery", "A City of Opportunity"] },
    bilingual: { label: "The advantage of bilingualism", title: "Learn two global languages in everyday life.", description: "Few cities offer such a natural environment for developing both French and English through study, work, friendship, culture, and daily communication.", benefits: [{ title: "Communication", description: "Express ideas with greater range and confidence across academic, social, and professional settings." }, { title: "Career opportunity", description: "Access roles and networks that value bilingual collaboration in Québec, Canada, and international markets." }, { title: "Global mobility", description: "Use two widely connected languages to study, work, and build relationships across countries." }, { title: "Intercultural competence", description: "Learn to listen, adapt, interpret context, and communicate respectfully across cultures." }], statements: ["French Opens Doors in Québec and Beyond", "English Connects You to the World", "Bilingualism Creates a Competitive Advantage"] },
    welcome: { label: "A safe and welcoming city", title: "A place where international students can feel at home.", description: "Moving to a new country is a major transition. Montréal is known for openness, neighbourhood life, cultural plurality, and communities where different identities and experiences are visible and valued.", tags: ["Inclusive Communities", "Cultural Diversity", "International Student-Friendly", "Exceptional Quality of Life"], quote: "Montréal is not only a place to study. It is a place to belong." },
    innovation: { label: "A center of innovation", title: "Learn in one of North America's most creative economies.", description: "Research, entrepreneurship, design, and technology are woven into the city's universities, companies, institutes, and public life.", sectors: [{ title: "Artificial intelligence", description: "Research, machine learning, responsible AI, data, and intelligent systems." }, { title: "Aerospace", description: "Aircraft, engineering, simulation, manufacturing, and international supply networks." }, { title: "Life sciences", description: "Health research, biotechnology, pharmaceuticals, clinical innovation, and medical technology." }, { title: "Technology", description: "Software, gaming, cybersecurity, digital platforms, and emerging ventures." }, { title: "Engineering", description: "Infrastructure, energy, advanced systems, transportation, and sustainable design." }, { title: "Creative industries", description: "Film, visual effects, games, design, music, media, and cultural entrepreneurship." }], slogans: ["Think Creatively", "Innovate Boldly", "Build the Future"] },
    culture: { label: "Culture, arts & experiences", title: "A city full of life in every season.", description: "Montréal turns free time into discovery, with experiences that help students understand the city, meet people, practise languages, and build a life beyond the classroom.", experiences: [{ title: "International festivals", description: "Major celebrations of jazz, comedy, cinema, performance, food, culture, and community." }, { title: "Museums & galleries", description: "Collections and exhibitions spanning history, design, science, contemporary art, and global culture." }, { title: "Music & performing arts", description: "Concerts, theatre, dance, opera, independent venues, and multilingual creative scenes." }, { title: "Sporting events", description: "Professional teams, university sport, community leagues, recreation, and year-round fitness." }, { title: "Culinary experiences", description: "Québec traditions and food cultures from across the world, from markets to neighbourhood restaurants." }, { title: "Outdoor activities", description: "Parks, cycling, hiking, skating, skiing, waterfronts, and seasonal exploration." }] },
    career: { label: "Career opportunities", title: "A launchpad for future professional success.", description: "Montréal's economic and research ecosystems create opportunities to learn how industries work, meet professionals, and develop experience alongside academic study.", ecosystem: [{ title: "Global companies", description: "International employers and Canadian leaders across finance, technology, engineering, retail, media, and services." }, { title: "Research centers", description: "University, hospital, public, and industry research teams working on complex real-world challenges." }, { title: "Start-up ecosystem", description: "Entrepreneurs, incubators, accelerators, investors, and early-stage companies building new products and services." }, { title: "International organizations", description: "Institutions and networks connected to aviation, global affairs, culture, development, and cooperation." }, { title: "Technology innovators", description: "Fast-moving teams in AI, software, gaming, digital media, health technology, and advanced manufacturing." }], slogans: ["Learn Today", "Lead Tomorrow"] },
    studentLife: { label: "Student life in Montréal", title: "Balance academic ambition with a rich daily life.", description: "The city supports focused study and personal wellbeing through accessible places to work, rest, connect, and explore.", items: [{ title: "Cafés & study spaces", description: "Libraries, campus facilities, neighbourhood cafés, and shared spaces for individual work and group study." }, { title: "Parks & green spaces", description: "Places to walk, exercise, meet friends, recharge, and enjoy the city's changing seasons." }, { title: "Public transportation", description: "Metro, bus, REM, cycling, and walkable neighbourhoods make the metropolitan region accessible." }, { title: "Diverse neighbourhoods", description: "Distinct areas offer different architecture, languages, food, music, shops, and community experiences." }] },
    citizens: { label: "A city that inspires global citizens", title: "Living abroad develops abilities that classrooms alone cannot teach.", description: "By navigating a bilingual, multicultural city, students become more independent, resilient, communicative, and aware of the wider world.", qualities: [{ title: "Independence", description: "Make decisions, manage responsibilities, and build routines in a new environment." }, { title: "Resilience", description: "Respond constructively to change, uncertainty, challenge, and unfamiliar situations." }, { title: "Cultural exploration", description: "Approach difference with curiosity and learn from communities beyond one's own experience." }, { title: "Communication", description: "Listen closely, adapt language, explain ideas, and connect across backgrounds." }, { title: "International perspective", description: "Understand local choices in relation to wider social, economic, cultural, and global realities." }], slogans: ["Grow Personally", "Learn Globally", "Succeed Internationally"] },
    cta: { label: "Your future begins here", title: "Make Montréal Your Next Destination", description: "Choose more than a place to study. Choose a city where languages, knowledge, culture, innovation, and opportunity become part of your education.", motto: "A World-Class City for World-Class Education", actions: ["Apply Now", "Request Information", "Schedule a Consultation"] },
  },
  fr: {
    hero: { eyebrow: "Pourquoi Montréal", title: "Pourquoi étudier à Montréal?", subtitle: "Une ville où se rencontrent éducation, innovation et possibilités", description: "Choisir une université est important; choisir la ville où vivre, apprendre et grandir l'est tout autant. Montréal réunit excellence académique, diversité culturelle, possibilités économiques et qualité de vie.", slogans: ["Étudier dans une ville mondiale", "Construire un avenir international", "Vivre sans limites"] },
    destination: { label: "Une destination éducative mondiale", title: "Une ville bâtie pour les étudiants, les idées et la découverte.", description: "Chaque année, Montréal accueille des apprenants dans un milieu façonné par les universités, la recherche, la créativité et l'échange.", items: [{ title: "Éducation de calibre mondial", description: "Universités, collèges, bibliothèques, laboratoires et communautés académiques." }, { title: "Diversité internationale", description: "Langues, cultures, traditions et perspectives de toutes les régions du monde." }, { title: "Vie étudiante abordable", description: "Une valeur avantageuse pour le logement, le transport, l'alimentation et la culture parmi les grandes villes nord-américaines." }, { title: "Possibilités de carrière", description: "Des industries en croissance, employeurs, chercheurs, entrepreneurs et réseaux." }, { title: "Culture dynamique", description: "Festivals, arts, musique, cuisine, sport et vie de quartier." }], tags: ["Ville d'apprentissage", "Ville de découverte", "Ville de possibilités"] },
    bilingual: { label: "L'avantage du bilinguisme", title: "Apprendre deux langues mondiales au quotidien.", description: "Peu de villes offrent un milieu aussi naturel pour développer français et anglais par les études, le travail, les amitiés et la culture.", benefits: [{ title: "Communication", description: "Exprimer ses idées avec plus d'aisance dans les milieux académiques, sociaux et professionnels." }, { title: "Possibilités de carrière", description: "Accéder aux rôles et réseaux qui valorisent la collaboration bilingue." }, { title: "Mobilité mondiale", description: "Utiliser deux langues pour étudier, travailler et créer des liens entre pays." }, { title: "Compétence interculturelle", description: "Écouter, s'adapter et communiquer avec respect entre cultures." }], statements: ["Le français ouvre des portes au Québec et ailleurs", "L'anglais vous relie au monde", "Le bilinguisme crée un avantage concurrentiel"] },
    welcome: { label: "Une ville sécuritaire et accueillante", title: "Un lieu où les étudiants internationaux peuvent se sentir chez eux.", description: "S'installer dans un nouveau pays est une transition majeure. Montréal est reconnue pour son ouverture, sa diversité et ses communautés accueillantes.", tags: ["Communautés inclusives", "Diversité culturelle", "Milieu accueillant pour étudiants", "Qualité de vie exceptionnelle"], quote: "Montréal n'est pas seulement un lieu d'études. C'est un lieu d'appartenance." },
    innovation: { label: "Un centre d'innovation", title: "Apprendre dans l'une des économies les plus créatives d'Amérique du Nord.", description: "Recherche, entrepreneuriat, design et technologie sont présents dans les universités, entreprises et instituts.", sectors: [{ title: "Intelligence artificielle", description: "Recherche, apprentissage automatique, IA responsable et données." }, { title: "Aérospatiale", description: "Aéronefs, ingénierie, simulation, fabrication et chaînes mondiales." }, { title: "Sciences de la vie", description: "Santé, biotechnologies, pharmaceutique et technologies médicales." }, { title: "Technologie", description: "Logiciels, jeux, cybersécurité, plateformes numériques et jeunes pousses." }, { title: "Génie", description: "Infrastructures, énergie, systèmes, transport et design durable." }, { title: "Industries créatives", description: "Cinéma, effets visuels, jeux, design, musique et médias." }], slogans: ["Penser avec créativité", "Innover avec audace", "Bâtir l'avenir"] },
    culture: { label: "Culture, arts et expériences", title: "Une ville vivante en toute saison.", description: "Montréal transforme les loisirs en découverte et aide à comprendre la ville, rencontrer des gens et pratiquer les langues.", experiences: [{ title: "Festivals internationaux", description: "Jazz, humour, cinéma, arts, cuisine, culture et communauté." }, { title: "Musées et galeries", description: "Histoire, design, science, art contemporain et cultures mondiales." }, { title: "Musique et scène", description: "Concerts, théâtre, danse, opéra et scènes créatives multilingues." }, { title: "Événements sportifs", description: "Équipes professionnelles, sport universitaire, ligues et loisirs." }, { title: "Expériences culinaires", description: "Traditions québécoises et cuisines du monde, marchés et restaurants." }, { title: "Activités de plein air", description: "Parcs, vélo, randonnée, patin, ski et rives." }] },
    career: { label: "Possibilités de carrière", title: "Un tremplin pour la réussite professionnelle.", description: "Les écosystèmes économiques et de recherche permettent de comprendre les industries, rencontrer des professionnels et développer son expérience.", ecosystem: [{ title: "Entreprises mondiales", description: "Employeurs en finance, technologie, génie, commerce, médias et services." }, { title: "Centres de recherche", description: "Équipes universitaires, hospitalières, publiques et industrielles." }, { title: "Écosystème de jeunes pousses", description: "Entrepreneurs, incubateurs, accélérateurs, investisseurs et nouvelles entreprises." }, { title: "Organisations internationales", description: "Aviation, affaires mondiales, culture, développement et coopération." }, { title: "Innovateurs technologiques", description: "IA, logiciels, jeux, médias numériques, santé et fabrication avancée." }], slogans: ["Apprendre aujourd'hui", "Diriger demain"] },
    studentLife: { label: "Vie étudiante à Montréal", title: "Équilibrer ambition académique et vie quotidienne riche.", description: "La ville offre des lieux accessibles pour travailler, se reposer, créer des liens et explorer.", items: [{ title: "Cafés et espaces d'étude", description: "Bibliothèques, campus, cafés de quartier et espaces partagés." }, { title: "Parcs et espaces verts", description: "Marcher, bouger, voir ses amis et profiter des saisons." }, { title: "Transport public", description: "Métro, autobus, REM, vélo et quartiers accessibles à pied." }, { title: "Quartiers diversifiés", description: "Architecture, langues, cuisines, musique, commerces et communautés." }] },
    citizens: { label: "Une ville qui inspire les citoyens du monde", title: "Vivre à l'étranger développe des capacités uniques.", description: "Dans une ville bilingue et multiculturelle, les étudiants deviennent plus autonomes, résilients et ouverts.", qualities: [{ title: "Autonomie", description: "Décider, gérer ses responsabilités et bâtir des habitudes." }, { title: "Résilience", description: "Réagir au changement, à l'incertitude et aux défis." }, { title: "Exploration culturelle", description: "Aborder la différence avec curiosité." }, { title: "Communication", description: "Écouter, adapter la langue et créer des liens." }, { title: "Perspective internationale", description: "Relier les choix locaux aux réalités mondiales." }], slogans: ["Grandir personnellement", "Apprendre mondialement", "Réussir internationalement"] },
    cta: { label: "Votre avenir commence ici", title: "Faites de Montréal votre prochaine destination", description: "Choisissez une ville où langues, savoir, culture, innovation et possibilités font partie de votre éducation.", motto: "Une ville de calibre mondial pour une éducation de calibre mondial", actions: ["Faire une demande", "Demander de l'information", "Planifier une consultation"] },
  },
  zh: {
    hero: { eyebrow: "为什么选择蒙特利尔", title: "为什么在蒙特利尔学习？", subtitle: "教育、创新与机遇交汇的城市", description: "选择大学很重要，选择生活、学习和成长的城市同样重要。蒙特利尔将学术卓越、文化多元、经济机会和高品质生活汇聚于一座真正国际化的学生城市。", slogans: ["在全球城市学习", "建设国际化未来", "体验无限生活"] },
    destination: { label: "全球教育目的地", title: "一座适合学生、思想与发现共同生长的城市。", description: "每年，蒙特利尔吸引来自加拿大和世界各地的学生，进入一个由大学、研究、创造力与开放交流共同塑造的环境。", items: [{ title: "世界级教育环境", description: "密集的大学、学院、图书馆、实验室及学术社区网络。" }, { title: "国际文化多元", description: "在日常生活中接触来自全球的语言、文化、传统和观点。" }, { title: "留学性价比", description: "与北美许多主要留学城市相比，住房、交通、饮食和文化生活具有较强价值。" }, { title: "强劲就业机会", description: "连接增长行业、雇主、研究者、创业者及专业网络。" }, { title: "活跃文化生活", description: "节庆、艺术、音乐、美食、体育和社区生活让课堂外也充满学习。" }], tags: ["学习之城", "发现之城", "机遇之城"] },
    bilingual: { label: "双语优势", title: "在日常生活中发展两种全球语言。", description: "很少有城市能够让学生如此自然地通过学习、工作、友谊、文化和日常交流同步发展法语与英语。", benefits: [{ title: "沟通能力", description: "在学术、社交和职业环境中以更丰富的方式自信表达。" }, { title: "职业机会", description: "进入魁北克、加拿大和国际市场中重视双语合作的职位与网络。" }, { title: "全球流动性", description: "使用两种广泛连接世界的语言跨国学习、工作和建立关系。" }, { title: "跨文化能力", description: "学习倾听、适应、理解语境，并在不同文化之间尊重沟通。" }], statements: ["法语开启魁北克及更广阔世界的门", "英语连接世界", "双语创造竞争优势"] },
    welcome: { label: "安全友好的城市", title: "让国际学生能够感到安心与归属。", description: "移居和留学是人生中的重大转变。蒙特利尔以开放、社区生活和文化多元闻名，不同身份与经历都能被看见和尊重。", tags: ["包容社区", "文化多元", "国际学生友好环境", "优质生活"], quote: "蒙特利尔不仅是求学之地，更是归属之地。" },
    innovation: { label: "创新中心", title: "在北美最具创造力的经济环境之一学习。", description: "研究、创业、设计和科技贯穿城市的大学、企业、研究机构和公共生活。", sectors: [{ title: "人工智能", description: "机器学习、负责任 AI、数据与智能系统。" }, { title: "航空航天", description: "飞机、工程、模拟、制造与国际供应网络。" }, { title: "生命科学", description: "健康研究、生物科技、制药、临床创新与医疗技术。" }, { title: "科技", description: "软件、游戏、网络安全、数字平台与新兴企业。" }, { title: "工程", description: "基础设施、能源、先进系统、交通与可持续设计。" }, { title: "创意产业", description: "影视、视觉特效、游戏、设计、音乐、媒体与文化创业。" }], slogans: ["创造性思考", "大胆创新", "建设未来"] },
    culture: { label: "文化艺术体验", title: "四季都充满活力的城市。", description: "蒙特利尔让课余时间也成为发现，帮助学生理解城市、认识朋友、练习语言并建设课堂外的生活。", experiences: [{ title: "国际艺术节", description: "爵士、喜剧、电影、表演、美食、文化与社区庆典。" }, { title: "博物馆与画廊", description: "历史、设计、科学、当代艺术和世界文化展览。" }, { title: "音乐与表演艺术", description: "音乐会、戏剧、舞蹈、歌剧和多语言创意现场。" }, { title: "体育赛事", description: "职业球队、大学体育、社区联赛、娱乐和全年运动。" }, { title: "美食体验", description: "从市场到社区餐厅，体验魁北克传统和全球饮食文化。" }, { title: "户外活动", description: "公园、骑行、徒步、滑冰、滑雪及滨水活动。" }] },
    career: { label: "职业发展机会", title: "通往未来职业成功的起点。", description: "蒙特利尔的经济与研究生态让学生了解行业、认识专业人士，并在学术学习之外积累实际经验。", ecosystem: [{ title: "全球企业", description: "金融、科技、工程、零售、媒体和服务行业的重要雇主。" }, { title: "科研中心", description: "大学、医院、政府及产业团队共同回应现实挑战。" }, { title: "初创生态", description: "创业者、孵化器、加速器、投资者及早期企业。" }, { title: "国际组织", description: "连接航空、全球事务、文化、发展与国际合作。" }, { title: "科技创新公司", description: "人工智能、软件、游戏、数字媒体、医疗科技与先进制造。" }], slogans: ["今天学习", "明日引领"] },
    studentLife: { label: "蒙特利尔学生生活", title: "在学术理想与丰富日常之间取得平衡。", description: "城市提供便捷的学习、休息、连接和探索空间，支持专注学习与个人健康。", items: [{ title: "咖啡馆与学习空间", description: "图书馆、校园设施、社区咖啡馆和适合个人及团队学习的共享空间。" }, { title: "公园与绿地", description: "散步、运动、与朋友见面、恢复精力并体验城市四季。" }, { title: "便捷公共交通", description: "地铁、公交、REM、骑行和步行社区让整个都会区触手可及。" }, { title: "多元社区", description: "不同社区提供独特建筑、语言、美食、音乐、商店和文化体验。" }] },
    citizens: { label: "培养全球公民的城市", title: "有些能力，只有在真实生活中才会长出来。", description: "通过适应双语、多文化城市，学生将变得更加独立、坚韧、善于沟通，并逐步建立全球意识。", qualities: [{ title: "独立性", description: "在新环境中作决定、管理责任并建立日常秩序。" }, { title: "韧性", description: "建设性地面对变化、不确定性、挑战与陌生情况。" }, { title: "跨文化探索", description: "以好奇心面对差异，从不同社区和经历中学习。" }, { title: "沟通能力", description: "认真倾听、调整语言、解释观点并跨越背景建立连接。" }, { title: "国际视野", description: "将本地选择与更广泛的社会、经济、文化和全球现实联系。" }], slogans: ["个人成长", "全球学习", "国际成功"] },
    cta: { label: "你的未来从这里开始", title: "让蒙特利尔成为你的下一站。", description: "选择的不只是求学地点，更是一座让语言、知识、文化、创新和机会共同成为教育一部分的城市。", motto: "世界级城市，承载世界级教育", actions: ["立即申请", "索取资料", "预约咨询"] },
  },
};
