import Link from "next/link";
import Image from "next/image";
import { DocumentLanguage } from "@/components/document-language";
import { AboutHeroEffects } from "@/components/motion/about-hero-effects";
import { Reveal } from "@/components/motion/reveal";
import { StaggerGrid } from "@/components/motion/stagger-grid";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { SectionHeading } from "@/components/ui/section-heading";
import { aboutContent } from "@/content/about-content";
import type { Locale,SiteContent } from "@/content/site-content";

const heroMarkLabels: Record<Locale, { established: string; campus: string; focus: string }> = {
  en: { established: "Established", campus: "UdeM · Brossard Campus", focus: "Program focus" },
  fr: { established: "Fondé", campus: "Campus UdeM · Brossard", focus: "Axes du parcours" },
  zh: { established: "创立于", campus: "蒙大 · Brossard 校区", focus: "课程重点" },
};

const aboutImageLabels: Record<Locale, { story: string; mission: string; community: string; communityAlt: string }> = {
  en: { story: "A university setting with real academic depth", mission: "Preparation inside a broader campus environment", community: "International student community", communityAlt: "Campus context for shared learning" },
  fr: { story: "Un véritable cadre universitaire", mission: "La préparation dans un environnement de campus", community: "Communauté étudiante internationale", communityAlt: "Un contexte de campus pour apprendre ensemble" },
  zh: { story: "真实而深厚的大学环境", mission: "校园环境中的学术准备", community: "国际学生社区", communityAlt: "共同学习的校园背景" },
};

export function AboutPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=aboutContent[locale];const heroMark=heroMarkLabels[locale];const imageLabels=aboutImageLabels[locale];return <div lang={chrome.htmlLang}>
<DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="abHero"><AboutHeroEffects/><div className="abHeroPattern"/><div className="shell abHeroGrid"><Reveal><p className="eyebrow">{p.hero.eyebrow}</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="abSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="abHeroMark"><div className="abHeroMarkTop"><span>{heroMark.established}</span><strong>1992</strong></div><div className="abHeroMarkBody"><p>{heroMark.focus}</p>{p.story.elements.slice(0,3).map((item,index)=><article key={item.title}><span>0{index+1}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div><small>{heroMark.campus}</small></div></div></section>
<section className="abDirector contentSection"><div className="shell abDirectorGrid"><div className="abPortrait"><span>OFFICE OF THE DIRECTOR</span><strong>Leadership<br/>with Purpose</strong><small>UdeM · Brossard Campus</small></div><Reveal><p className="sectionLabel">{p.director.label}</p><h2>{p.director.title}</h2><p>{p.director.message}</p><blockquote>{p.director.quote}</blockquote><small>{p.director.signature}</small></Reveal></div></section>
<section className="abStory contentSection"><div className="shell"><Reveal><SectionHeading label={p.story.label} title={p.story.title} description={p.story.description}/></Reveal><StaggerGrid className="abFourGrid">{p.story.elements.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid><figure className="abStoryPhoto"><Image src="/M/building 19.jpg" alt={imageLabels.story} fill sizes="(max-width: 760px) 100vw, 1180px"/><figcaption><span>01</span>{imageLabels.story}</figcaption></figure><div className="abStorySlogans">{p.story.slogans.map(x=><strong key={x}>{x}</strong>)}</div></div></section>
<section className="abMission contentSection"><div className="shell abMissionIntro"><Reveal><SectionHeading light label={p.mission.label} title={p.mission.title} description={p.mission.description}/></Reveal><figure className="abMissionPhoto"><Image src="/M/building 17.jpg" alt={imageLabels.mission} fill sizes="(max-width: 900px) 100vw, 34vw"/><figcaption>{imageLabels.mission}</figcaption></figure></div><div className="shell"><div className="abFourGrid abFourLight">{p.mission.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="abVision contentSection"><div className="shell abVisionGrid"><Reveal><p className="sectionLabel">{p.vision.label}</p><h2>{p.vision.title}</h2><p>{p.vision.description}</p><div className="abVisionSlogans">{p.vision.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="abAmbitions">{p.vision.ambitions.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="abPhilosophy contentSection"><div className="shell"><Reveal><SectionHeading label={p.philosophy.label} title={p.philosophy.title} description={p.philosophy.description}/></Reveal><div className="abFiveGrid">{p.philosophy.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="abExcellence contentSection"><div className="shell abExcellenceGrid"><Reveal><p className="sectionLabel">{p.excellence.label}</p><h2>{p.excellence.title}</h2><p>{p.excellence.description}</p></Reveal><div><div className="abCapabilities">{p.excellence.capabilities.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div><blockquote>{p.excellence.quote}</blockquote></div></div></section>
<section className="abCommunity contentSection"><div className="shell"><Reveal><SectionHeading label={p.community.label} title={p.community.title} description={p.community.description}/></Reveal><div className="abCommunityPhotos"><figure><Image src="/M/people 2.jpg" alt={imageLabels.community} fill sizes="(max-width: 760px) 100vw, 48vw"/><figcaption>{imageLabels.community}</figcaption></figure><figure><Image src="/M/building 15.jpg" alt={imageLabels.communityAlt} fill sizes="(max-width: 760px) 100vw, 34vw"/><figcaption>{imageLabels.communityAlt}</figcaption></figure></div><StaggerGrid className="abFourGrid">{p.community.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid><div className="abCommunitySlogans">{p.community.slogans.map(x=><strong key={x}>{x}</strong>)}</div></div></section>
<section className="abCommitment contentSection"><div className="shell"><Reveal><SectionHeading light label={p.commitment.label} title={p.commitment.title} description={p.commitment.description}/></Reveal><div className="abCommitmentList">{p.commitment.services.map((x,i)=><article key={x.title}><span>0{i+1}</span><div><h3>{x.title}</h3><p>{x.description}</p></div></article>)}</div></div></section>
<section className="abValues contentSection"><div className="shell"><Reveal><SectionHeading label={p.values.label} title={p.values.title} description={p.values.description}/></Reveal><div className="abValuesManifesto">{p.values.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="abCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><div className="abMotto">{p.cta.motto.map(x=><span key={x}>{x}</span>)}</div><div className="abCtaActions"><Link className="button lightButton" href={`/${locale}/apply`}>{p.cta.actions[0]}<span>↗</span></Link><Link className="textLink" href={`/${locale}/leadership`}>{p.cta.actions[1]}<span>→</span></Link><Link className="textLink" href={`/${locale}/contact`}>{p.cta.actions[2]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
