import Link from "next/link";
import { DocumentLanguage } from "@/components/document-language";
import { Reveal } from "@/components/motion/reveal";
import { StaggerGrid } from "@/components/motion/stagger-grid";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { SectionHeading } from "@/components/ui/section-heading";
import { aboutContent } from "@/content/about-content";
import type { Locale,SiteContent } from "@/content/site-content";

export function AboutPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=aboutContent[locale];return <div lang={chrome.htmlLang}>
<DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="abHero"><div className="abHeroPattern"/><div className="shell abHeroGrid"><Reveal><p className="eyebrow">{p.hero.eyebrow}</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="abSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="abHeroMark"><span>ESTABLISHED</span><strong>1992</strong><small>EXCELLENCE · OPPORTUNITY</small></div></div></section>
<section className="abDirector contentSection"><div className="shell abDirectorGrid"><div className="abPortrait"><span>OFFICE OF THE DIRECTOR</span><strong>Leadership<br/>with Purpose</strong><small>UdeM · Brossard Campus</small></div><Reveal><p className="sectionLabel">{p.director.label}</p><h2>{p.director.title}</h2><p>{p.director.message}</p><blockquote>{p.director.quote}</blockquote><small>{p.director.signature}</small></Reveal></div></section>
<section className="abStory contentSection"><div className="shell"><Reveal><SectionHeading label={p.story.label} title={p.story.title} description={p.story.description}/></Reveal><StaggerGrid className="abFourGrid">{p.story.elements.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid><div className="abStorySlogans">{p.story.slogans.map(x=><strong key={x}>{x}</strong>)}</div></div></section>
<section className="abMission contentSection"><div className="shell"><Reveal><SectionHeading light label={p.mission.label} title={p.mission.title} description={p.mission.description}/></Reveal><div className="abFourGrid abFourLight">{p.mission.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="abVision contentSection"><div className="shell abVisionGrid"><Reveal><p className="sectionLabel">{p.vision.label}</p><h2>{p.vision.title}</h2><p>{p.vision.description}</p><div className="abVisionSlogans">{p.vision.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="abAmbitions">{p.vision.ambitions.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="abPhilosophy contentSection"><div className="shell"><Reveal><SectionHeading label={p.philosophy.label} title={p.philosophy.title} description={p.philosophy.description}/></Reveal><div className="abFiveGrid">{p.philosophy.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="abExcellence contentSection"><div className="shell abExcellenceGrid"><Reveal><p className="sectionLabel">{p.excellence.label}</p><h2>{p.excellence.title}</h2><p>{p.excellence.description}</p></Reveal><div><div className="abCapabilities">{p.excellence.capabilities.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div><blockquote>{p.excellence.quote}</blockquote></div></div></section>
<section className="abCommunity contentSection"><div className="shell"><Reveal><SectionHeading label={p.community.label} title={p.community.title} description={p.community.description}/></Reveal><StaggerGrid className="abFourGrid">{p.community.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid><div className="abCommunitySlogans">{p.community.slogans.map(x=><strong key={x}>{x}</strong>)}</div></div></section>
<section className="abCommitment contentSection"><div className="shell"><Reveal><SectionHeading light label={p.commitment.label} title={p.commitment.title} description={p.commitment.description}/></Reveal><div className="abCommitmentList">{p.commitment.services.map((x,i)=><article key={x.title}><span>0{i+1}</span><div><h3>{x.title}</h3><p>{x.description}</p></div></article>)}</div></div></section>
<section className="abValues contentSection"><div className="shell"><Reveal><SectionHeading label={p.values.label} title={p.values.title} description={p.values.description}/></Reveal><div className="abValuesManifesto">{p.values.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="abCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><div className="abMotto">{p.cta.motto.map(x=><span key={x}>{x}</span>)}</div><div className="abCtaActions"><Link className="button lightButton" href={`/${locale}/apply`}>{p.cta.actions[0]}<span>↗</span></Link><Link className="textLink" href={`/${locale}/leadership`}>{p.cta.actions[1]}<span>→</span></Link><Link className="textLink" href={`/${locale}/contact`}>{p.cta.actions[2]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
