import Link from"next/link";import Image from"next/image";import{DocumentLanguage}from"@/components/document-language";import{Reveal}from"@/components/motion/reveal";import{StaggerGrid}from"@/components/motion/stagger-grid";import{SiteFooter}from"@/components/site-footer";import{SiteHeader}from"@/components/site-header";import{HeroInfoCard}from"@/components/ui/hero-info-card";import{SectionHeading}from"@/components/ui/section-heading";import{academicFoundationContent}from"@/content/academic-foundation-content";import type{Locale,SiteContent}from"@/content/site-content";
function Stream({stream,code,dark=false}:{stream:{label:string;title:string;description:string;meta:string;price:string;subjects:{title:string;description:string}[];pathways:string[]};code:string;dark?:boolean}){return <section className={`afStream contentSection ${dark?"afStreamDark":""}`}><div className="shell"><div className="afStreamHead"><Reveal><p className="sectionLabel">{stream.label}</p><h2>{stream.title}</h2><p>{stream.description}</p></Reveal><div><strong>{code}</strong><span>{stream.meta}</span><b>{stream.price}</b></div></div><div className="afSubjectGrid">{stream.subjects.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div><div className="afPathways">{stream.pathways.map(x=><span key={x}>{x}</span>)}</div></div></section>}
export function AcademicFoundationPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=academicFoundationContent[locale];return <div lang={chrome.htmlLang}><DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="afHero"><div className="afHeroPattern"/><div className="shell afHeroGrid"><Reveal><p className="eyebrow">{p.hero.eyebrow}</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="afSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div><div className="heroActions"><Link className="button" href={`/${locale}/apply`}>{p.hero.actions[0]}<span>↗</span></Link><a className="textLink" href="mailto:admissions@UDEMIC.ca">{p.hero.actions[1]}<span>→</span></a></div></Reveal><div className="afHeroMark heroInfoCard"><HeroInfoCard eyebrow="Academic foundation" title="3 streams" focus="Preparation paths" items={p.hero.slogans} footer="Business · STEM · Social sciences"/></div></div></section>
<section className="afDefinition contentSection"><div className="shell"><Reveal><SectionHeading label={p.definition.label} title={p.definition.title} description={p.definition.description}/></Reveal><figure className="afWidePhoto"><Image src="/M/inside 2.jpg" alt="Modern academic learning space for foundation studies" fill sizes="(max-width: 760px) 100vw, 1180px"/><figcaption>Academic habits built in a university-oriented setting</figcaption></figure><StaggerGrid className="afSixGrid">{p.definition.capabilities.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid></div></section>
<section className="afPathwayProgram contentSection"><div className="shell"><Reveal><SectionHeading light label={p.pathway.label} title={p.pathway.title} description={p.pathway.description}/></Reveal><div className="afFiveGrid afFiveLight">{p.pathway.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<Stream stream={p.business} code="BUS"/><Stream stream={p.stem} code="STEM" dark/><Stream stream={p.social} code="SOC"/>
<section className="afSkills contentSection"><div className="shell afSkillsLayout"><figure className="afSidePhoto"><Image src="/c/library 2.jpg" alt="Students working with library and research resources" fill sizes="(max-width: 900px) 100vw, 38vw"/><figcaption>Research, reading, and academic methods</figcaption></figure><div><Reveal><SectionHeading label={p.skills.label} title={p.skills.title} description={p.skills.description}/></Reveal><div className="afSixGrid">{p.skills.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></div></section>
<section className="afEnvironment contentSection"><div className="shell afEnvironmentGrid"><div className="afCampusVisual"><span>UdeM BROSSARD CAMPUS</span><strong>LEARN<br/>THINK<br/>SUCCEED</strong><small>UNIVERSITY ENVIRONMENT</small></div><Reveal><p className="sectionLabel">{p.environment.label}</p><h2>{p.environment.title}</h2><p>{p.environment.description}</p><div className="afExperiences">{p.environment.experiences.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div><div className="afEnvSlogans">{p.environment.slogans.map(x=><strong key={x}>{x}</strong>)}</div></Reveal></div></section>
<section className="afProgression contentSection"><div className="shell"><Reveal><SectionHeading label={p.progression.label} title={p.progression.title} description={p.progression.description}/></Reveal><div className="afFlow">{p.progression.steps.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="afCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><div className="afFields">{p.cta.fields.map(x=><span key={x}>{x}</span>)}</div><strong className="afMotto">{p.cta.motto}</strong><div className="afCtaActions"><Link className="button lightButton" href={`/${locale}/apply`}>{p.cta.actions[0]}<span>↗</span></Link><a className="textLink" href="mailto:admissions@UDEMIC.ca">{p.cta.actions[1]}<span>→</span></a><Link className="textLink" href={`/${locale}/contact`}>{p.cta.actions[2]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
