import{DocumentLanguage}from"@/components/document-language";import{Reveal}from"@/components/motion/reveal";import{SiteFooter}from"@/components/site-footer";import{SiteHeader}from"@/components/site-header";import{SectionHeading}from"@/components/ui/section-heading";import{contactPageContent}from"@/content/final-pages-content";import type{Locale,SiteContent}from"@/content/site-content";
import{ContactInquiryForm}from"@/components/contact-inquiry-form";
const contactLabels={en:{campus:"UdeM Brossard Campus",center:"International Language & Pathway Center",address:"Address",telephone:"Telephone",admissions:"Admissions",services:"Student Services"},fr:{campus:"Campus UdeM Brossard",center:"Centre international de langues et de parcours",address:"Adresse",telephone:"Téléphone",admissions:"Admissions",services:"Services aux étudiants"},zh:{campus:"蒙大 Brossard 校区",center:"国际语言与大学衔接中心",address:"校区地址",telephone:"联系电话",admissions:"招生咨询",services:"学生服务"}};
export function ContactPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=contactPageContent[locale];const labels=contactLabels[locale];return <div lang={chrome.htmlLang}><DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="ctHero"><div className="shell"><Reveal><p className="eyebrow">Contact Us</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="ctSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal></div></section>
<section className="ctInfo contentSection"><div className="shell ctInfoGrid"><div><p className="sectionLabel">{labels.campus}</p><h2>{labels.center}</h2></div><div className="ctDetails"><article><span>{labels.address}</span><strong>2000 Rue de l&apos;Éclipse<br/>Brossard, Québec, Canada</strong></article><article><span>{labels.telephone}</span><a href="tel:+14166661860">+1 (416) 666-1860</a></article><article><span>{labels.admissions}</span><a href="mailto:info@Montrealic.ca">info@Montrealic.ca</a></article></div></div></section>
<section className="ctVisit contentSection"><div className="shell"><Reveal><SectionHeading label={p.visit.label} title={p.visit.title} description={p.visit.description}/></Reveal><div className="ctVisitGrid">{p.visit.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="ctFormSection contentSection"><div className="shell ctFormGrid"><Reveal><p className="sectionLabel">{p.form.label}</p><h2>{p.form.title}</h2><p>{p.form.description}</p></Reveal><ContactInquiryForm button={p.form.button} fields={p.form.fields} programs={p.form.programs} success={locale==="zh"?"咨询已收到":locale==="fr"?"Demande reçue":"Inquiry received"}/></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
