import Link from"next/link";import{DocumentLanguage}from"@/components/document-language";import{Reveal}from"@/components/motion/reveal";import{StaggerGrid}from"@/components/motion/stagger-grid";import{SiteFooter}from"@/components/site-footer";import{SiteHeader}from"@/components/site-header";import{SectionHeading}from"@/components/ui/section-heading";import{languagePreparationContent}from"@/content/language-preparation-content";import type{Locale,SiteContent}from"@/content/site-content";
function ProgramBlock({program,code,dark=false}:{program:{title:string;description:string;meta:string;levels?:string[];skills:string[];price:string;slogans?:string[]};code:string;dark?:boolean}){return <section className={`lpProgram contentSection ${dark?"lpProgramDark":""}`}><div className="shell lpProgramGrid"><div className="lpProgramMark"><span>{code}</span><strong>{program.price}</strong><small>{program.meta}</small></div><div><Reveal><p className="sectionLabel">{program.meta}</p><h2>{program.title}</h2><p className="sectionDescription">{program.description}</p></Reveal>{program.levels&&<div className="lpLevels">{program.levels.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div>}<div className="lpSkills">{program.skills.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div>{program.slogans&&<div className="lpProgramSlogans">{program.slogans.map(x=><strong key={x}>{x}</strong>)}</div>}</div></div></section>}
export function LanguagePreparationPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=languagePreparationContent[locale];return <div lang={chrome.htmlLang}><DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="lpHero"><div className="lpHeroPattern"/><div className="shell lpHeroGrid"><Reveal><p className="eyebrow">{p.hero.eyebrow}</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="lpHeroSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="lpHeroMark"><span>FR · EN</span><strong>A1<br/>— C1</strong><small>LANGUAGE · ACADEMICS · FUTURE</small></div></div></section>
<section className="lpMeaning contentSection"><div className="shell"><Reveal><SectionHeading label={p.meaning.label} title={p.meaning.title} description={p.meaning.description}/></Reveal><StaggerGrid className="lpFiveGrid">{p.meaning.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid></div></section>
<ProgramBlock program={p.french} code="FR"/><ProgramBlock program={p.academicFrench} code="FR+" dark/><ProgramBlock program={p.english} code="EN"/><ProgramBlock program={p.academicEnglish} code="EN+" dark/><ProgramBlock program={p.intensive} code="INT"/>
<section className="lpMethod contentSection"><div className="shell"><Reveal><SectionHeading light label={p.method.label} title={p.method.title} description={p.method.description}/></Reveal><div className="lpFiveGrid lpFiveLight">{p.method.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="lpPathway contentSection"><div className="shell"><Reveal><SectionHeading label={p.pathway.label} title={p.pathway.title} description={p.pathway.description}/></Reveal><div className="lpFlow">{p.pathway.steps.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div><div className="lpPathSlogans">{p.pathway.slogans.map(x=><strong key={x}>{x}</strong>)}</div></div></section>
<section className="lpCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><strong className="lpMotto">{p.cta.motto}</strong><div className="lpCtaActions"><Link className="button lightButton" href={`/${locale}/apply`}>{p.cta.actions[0]}<span>↗</span></Link><a className="textLink" href="mailto:admissions@UDEMIC.ca">{p.cta.actions[1]}<span>→</span></a><Link className="textLink" href={`/${locale}/contact`}>{p.cta.actions[2]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
