import Link from "next/link";
import Image from "next/image";
import {DocumentLanguage} from "@/components/document-language";import {Reveal} from "@/components/motion/reveal";import {StaggerGrid} from "@/components/motion/stagger-grid";import {SiteFooter} from "@/components/site-footer";import {SiteHeader} from "@/components/site-header";import {HeroInfoCard} from "@/components/ui/hero-info-card";import {SectionHeading} from "@/components/ui/section-heading";import {leadershipContent} from "@/content/leadership-content";import type{Locale,SiteContent}from "@/content/site-content";
export function LeadershipPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=leadershipContent[locale];return <div lang={chrome.htmlLang}><DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="lgHero"><div className="lgHeroPattern"/><div className="shell lgHeroGrid"><Reveal><p className="eyebrow">{p.hero.eyebrow}</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="lgSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="lgHeroMark heroInfoCard"><HeroInfoCard eyebrow="Leadership" title="GOV" focus="Quality governance" items={p.hero.slogans} footer="Quality · Trust · Vision"/></div></div></section>
<section className="lgGovernance contentSection"><div className="shell"><Reveal><SectionHeading label={p.governance.label} title={p.governance.title} description={p.governance.description}/></Reveal><figure className="lgWidePhoto"><Image src="/M/meeting room 1.jpg" alt="Leadership and governance meeting space" fill sizes="(max-width: 760px) 100vw, 1180px"/><figcaption>Governance made visible through clear roles and review</figcaption></figure><StaggerGrid className="lgFiveGrid">{p.governance.principles.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid></div></section>
<section className="lgDirector contentSection"><div className="shell lgDirectorGrid"><div className="lgDirectorVisual"><span>EXECUTIVE OFFICE</span><strong>IT</strong><small>{p.director.signature}</small></div><Reveal><p className="sectionLabel">{p.director.label}</p><h2>{p.director.title}</h2><p>{p.director.message}</p><p>{p.director.promise}</p><div className="lgProgression">{p.director.progression.map((x,i)=><strong key={x}><span>0{i+1}</span>{x}</strong>)}</div></Reveal></div></section>
<section className="lgBoard contentSection"><div className="shell"><Reveal><SectionHeading light label={p.board.label} title={p.board.title} description={p.board.description}/></Reveal><div className="lgFiveGrid lgFiveLight">{p.board.responsibilities.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div><div className="lgTags">{p.board.tags.map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="lgTeam contentSection"><div className="shell"><Reveal><SectionHeading label={p.team.label} title={p.team.title} description={p.team.description}/></Reveal><figure className="lgTeamPhoto"><Image src="/M/inside 2.jpg" alt="Collaborative academic leadership environment" fill sizes="(max-width: 760px) 100vw, 1180px"/><figcaption>Academic leadership in context</figcaption></figure><div className="lgTeamGrid">{p.team.leaders.map((x,i)=><article key={x.name}><div className="lgAvatar"><span>{x.initials}</span><small>0{i+1}</small></div><p>{x.role}</p><h3>{x.name}</h3><div>{x.bio}</div></article>)}</div></div></section>
<section className="lgFaculty contentSection"><div className="shell"><Reveal><SectionHeading label={p.faculty.label} title={p.faculty.title} description={p.faculty.description}/></Reveal><div className="lgFiveGrid">{p.faculty.commitments.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div><div className="lgFacultySlogans">{p.faculty.slogans.map(x=><strong key={x}>{x}</strong>)}</div></div></section>
<section className="lgQuality contentSection"><div className="shell"><Reveal><SectionHeading light label={p.quality.label} title={p.quality.title} description={p.quality.description}/></Reveal><div className="lgQualityFlow">{p.quality.processes.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="lgValues contentSection"><div className="shell"><Reveal><SectionHeading label={p.values.label} title={p.values.title} description={p.values.description}/></Reveal><StaggerGrid className="lgSixGrid">{p.values.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid></div></section>
<section className="lgCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><strong className="lgMotto">{p.cta.motto}</strong><div className="lgCtaActions"><Link className="button lightButton" href={`/${locale}/leadership`}>{p.cta.actions[0]}<span>↗</span></Link><Link className="textLink" href={`/${locale}/programs`}>{p.cta.actions[1]}<span>→</span></Link><Link className="textLink" href={`/${locale}/contact`}>{p.cta.actions[2]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
