import Link from"next/link";import{DocumentLanguage}from"@/components/document-language";import{Reveal}from"@/components/motion/reveal";import{StaggerGrid}from"@/components/motion/stagger-grid";import{SiteFooter}from"@/components/site-footer";import{SiteHeader}from"@/components/site-header";import{SectionHeading}from"@/components/ui/section-heading";import{learningApproachContent}from"@/content/learning-approach-content";import type{Locale,SiteContent}from"@/content/site-content";
export function LearningApproachPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=learningApproachContent[locale];return <div lang={chrome.htmlLang}><DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="laHero"><div className="laPattern"/><div className="shell laHeroGrid"><Reveal><p className="eyebrow">Learning Approach</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="laSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="laMark"><span>LEARN</span><strong>01—04</strong><small>APPLY · REFLECT · GROW</small></div></div></section>
<section className="laPhilosophy contentSection"><div className="shell laTwo"><Reveal><p className="sectionLabel">{p.philosophy.label}</p><h2>{p.philosophy.title}</h2><p>{p.philosophy.description}</p></Reveal><div className="laActions">{p.philosophy.actions.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div></div></section>
<section className="laIntegration contentSection"><div className="shell laTwo"><div className="laIntegrationVisual"><span>LANGUAGE</span><strong>+</strong><span>ACADEMICS</span></div><Reveal><p className="sectionLabel">{p.integration.label}</p><h2>{p.integration.title}</h2><p>{p.integration.description}</p><div className="laIntegrationSlogans">{p.integration.slogans.map(x=><strong key={x}>{x}</strong>)}</div></Reveal></div></section>
<section className="laPractice contentSection"><div className="shell"><Reveal><SectionHeading label={p.practice.label} title={p.practice.title} description={p.practice.description}/></Reveal><StaggerGrid className="laFive">{p.practice.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid></div></section>
<section className="laSkills contentSection"><div className="shell"><Reveal><SectionHeading light label={p.skills.label} title={p.skills.title} description={p.skills.description}/></Reveal><div className="laSkillGrid">{p.skills.items.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="laSupport contentSection"><div className="shell"><Reveal><SectionHeading label={p.support.label} title={p.support.title} description={p.support.description}/></Reveal><div className="laFive">{p.support.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="laSmall contentSection"><div className="shell laTwo"><Reveal><p className="sectionLabel">{p.small.label}</p><h2>{p.small.title}</h2><p>{p.small.description}</p><div className="laSmallSlogans">{p.small.slogans.map(x=><strong key={x}>{x}</strong>)}</div></Reveal><div className="laBenefits">{p.small.benefits.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div></div></section>
<section className="laLeaders contentSection"><div className="shell"><Reveal><SectionHeading label={p.leaders.label} title={p.leaders.title} description={p.leaders.description}/></Reveal><div className="laFive">{p.leaders.qualities.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="laModel contentSection"><div className="shell"><Reveal><SectionHeading label={p.model.label} title={p.model.title} description={p.model.description}/></Reveal><div className="laFlow">{p.model.steps.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="laCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><div className="laStatements">{p.cta.statements.map(x=><blockquote key={x}>{x}</blockquote>)}</div><div className="laEndSlogans">{p.cta.slogans.map(x=><span key={x}>{x}</span>)}</div><div className="laCtaActions"><Link className="button lightButton" href={`/${locale}/programs`}>{p.cta.actions[0]}<span>↗</span></Link><Link className="textLink" href={`/${locale}/apply`}>{p.cta.actions[1]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
