import Link from"next/link";import Image from"next/image";import{DocumentLanguage}from"@/components/document-language";import{Reveal}from"@/components/motion/reveal";import{StaggerGrid}from"@/components/motion/stagger-grid";import{SiteFooter}from"@/components/site-footer";import{SiteHeader}from"@/components/site-header";import{SectionHeading}from"@/components/ui/section-heading";import{learningApproachContent}from"@/content/learning-approach-content";import type{Locale,SiteContent}from"@/content/site-content";
const learningImageLabels:Record<Locale,{philosophy:string;practice:string;support:string}>={
en:{philosophy:"Active learning in practice",practice:"Learning through applied work",support:"Guidance and collaboration"},
fr:{philosophy:"L'apprentissage actif en pratique",practice:"Apprendre par le travail appliqué",support:"Accompagnement et collaboration"},
zh:{philosophy:"实践中的主动学习",practice:"通过应用任务学习",support:"指导与协作"}
};
const heroPanelLabels:Record<Locale,{eyebrow:string;focus:string;footer:string}>={
en:{eyebrow:"Learning cycle",focus:"How students grow",footer:"Active practice · feedback · reflection"},
fr:{eyebrow:"Cycle d'apprentissage",focus:"Comment les étudiants progressent",footer:"Pratique active · rétroaction · réflexion"},
zh:{eyebrow:"学习循环",focus:"学生如何成长",footer:"主动实践 · 反馈 · 反思"}
};
export function LearningApproachPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=learningApproachContent[locale];const imageLabels=learningImageLabels[locale];const heroPanel=heroPanelLabels[locale];return <div lang={chrome.htmlLang}><DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="laHero"><div className="laPattern"/><div className="shell laHeroGrid"><Reveal><p className="eyebrow">Learning Approach</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p><div className="laSlogans">{p.hero.slogans.map(x=><span key={x}>{x}</span>)}</div></Reveal><div className="laMark"><div className="laMarkTop"><span>{heroPanel.eyebrow}</span><strong>01—04</strong></div><div className="laMarkBody"><p>{heroPanel.focus}</p>{p.philosophy.actions.slice(0,4).map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div><small>{heroPanel.footer}</small></div></div></section>
<section className="laPhilosophy contentSection"><div className="shell laTwo"><div><p className="sectionLabel">{p.philosophy.label}</p><h2>{p.philosophy.title}</h2><p>{p.philosophy.description}</p></div><div className="laPhilosophySide"><figure className="laPhilosophyPhoto"><Image src="/c/laptop study.jpg" alt={imageLabels.philosophy} fill sizes="(max-width: 900px) 100vw, 42vw"/><figcaption>{imageLabels.philosophy}</figcaption></figure><div className="laActions">{p.philosophy.actions.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div></div></div></section>
<section className="laIntegration contentSection"><div className="shell laTwo"><div className="laIntegrationVisual"><span>LANGUAGE</span><strong>+</strong><span>ACADEMICS</span></div><Reveal><p className="sectionLabel">{p.integration.label}</p><h2>{p.integration.title}</h2><p>{p.integration.description}</p><div className="laIntegrationSlogans">{p.integration.slogans.map(x=><strong key={x}>{x}</strong>)}</div></Reveal></div></section>
<section className="laPractice contentSection"><div className="shell"><Reveal><SectionHeading label={p.practice.label} title={p.practice.title} description={p.practice.description}/></Reveal><figure className="laPracticePhoto"><Image src="/c/learning from desktop.jpg" alt={imageLabels.practice} fill sizes="(max-width: 760px) 100vw, 1180px"/><figcaption><span>01</span>{imageLabels.practice}</figcaption></figure><StaggerGrid className="laFive">{p.practice.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</StaggerGrid></div></section>
<section className="laSkills contentSection"><div className="shell"><Reveal><SectionHeading light label={p.skills.label} title={p.skills.title} description={p.skills.description}/></Reveal><div className="laSkillGrid">{p.skills.items.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="laSupport contentSection"><div className="shell"><Reveal><SectionHeading label={p.support.label} title={p.support.title} description={p.support.description}/></Reveal><div className="laSupportFeature"><figure className="laSupportPhoto"><Image src="/c/team 1.jpg" alt={imageLabels.support} fill sizes="(max-width: 900px) 100vw, 58vw"/><figcaption>{imageLabels.support}</figcaption></figure><div className="laSupportFeatureCopy"><p className="sectionLabel">{p.support.items[0].title}</p><h3>{p.support.items[1].title}</h3><p>{p.support.items[1].description}</p></div></div><div className="laSupportGrid">{p.support.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="laSmall contentSection"><div className="shell laTwo"><Reveal><p className="sectionLabel">{p.small.label}</p><h2>{p.small.title}</h2><p>{p.small.description}</p><div className="laSmallSlogans">{p.small.slogans.map(x=><strong key={x}>{x}</strong>)}</div></Reveal><div className="laBenefits">{p.small.benefits.map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div></div></section>
<section className="laLeaders contentSection"><div className="shell"><Reveal><SectionHeading label={p.leaders.label} title={p.leaders.title} description={p.leaders.description}/></Reveal><div className="laFive">{p.leaders.qualities.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="laModel contentSection"><div className="shell"><Reveal><SectionHeading label={p.model.label} title={p.model.title} description={p.model.description}/></Reveal><div className="laFlow">{p.model.steps.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
<section className="laCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><div className="laStatements">{p.cta.statements.map(x=><blockquote key={x}>{x}</blockquote>)}</div><div className="laEndSlogans">{p.cta.slogans.map(x=><span key={x}>{x}</span>)}</div><div className="laCtaActions"><Link className="button lightButton" href={`/${locale}/programs`}>{p.cta.actions[0]}<span>↗</span></Link><Link className="textLink" href={`/${locale}/apply`}>{p.cta.actions[1]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
