import Link from"next/link";import{DocumentLanguage}from"@/components/document-language";import{Reveal}from"@/components/motion/reveal";import{SiteFooter}from"@/components/site-footer";import{SiteHeader}from"@/components/site-header";import{SectionHeading}from"@/components/ui/section-heading";import{tuitionPageContent}from"@/content/final-pages-content";import type{Locale,SiteContent}from"@/content/site-content";
export function TuitionPage({locale,chrome}:{locale:Locale;chrome:SiteContent}){const p=tuitionPageContent[locale];return <div lang={chrome.htmlLang}><DocumentLanguage lang={chrome.htmlLang}/><SiteHeader locale={locale} content={chrome.header}/><main>
<section className="tfHero"><div className="shell"><Reveal><p className="eyebrow">Tuition &amp; Fees</p><h1>{p.hero.title}</h1><p>{p.hero.description}</p></Reveal></div></section>
<section className="tfPrograms contentSection"><div className="shell"><Reveal><SectionHeading label={p.language.label} title={p.language.title} description={p.language.description}/></Reveal><div className="tfPriceGrid">{p.language.items.map(x=><article key={x.title}><strong>{x.price}</strong><span>{x.meta}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="tfFoundation contentSection"><div className="shell"><Reveal><SectionHeading light label={p.foundation.label} title={p.foundation.title} description={p.foundation.description}/></Reveal><div className="tfFoundationGrid">{p.foundation.items.map(x=><article key={x.title}><strong>{x.price}</strong><span>{x.meta}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="tfFees contentSection"><div className="shell"><Reveal><SectionHeading label={p.fees.label} title={p.fees.title}/></Reveal><div className="tfFeeList">{p.fees.items.map((x,i)=><div key={x.name}><span>0{i+1}</span><strong>{x.name}</strong><b>{x.amount}</b></div>)}</div></div></section>
<section className="tfPayment contentSection"><div className="shell"><Reveal><SectionHeading label={p.payment.label} title={p.payment.title} description={p.payment.description}/></Reveal><div className="tfPaymentGrid">{p.payment.items.map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.description}</p></article>)}</div></div></section>
<section className="tfCta"><div className="shell"><Reveal><p className="sectionLabel">{p.cta.label}</p><h2>{p.cta.title}</h2><p>{p.cta.description}</p><div className="tfCtaActions"><a className="button lightButton" href="mailto:info@Montrealic.ca">{p.cta.actions[0]}<span>↗</span></a><Link className="textLink" href={`/${locale}/contact`}>{p.cta.actions[1]}<span>→</span></Link></div></Reveal></div></section>
</main><SiteFooter content={chrome.footer} locale={locale}/></div>}
